// s10_configuration_clock_0.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module s10_configuration_clock_0 (
		output wire  clkout  // clkout.clk
	);

	altera_s10_configuration_clock s10_configuration_clock_0 (
		.clkout (clkout)  //  output,  width = 1, clkout.clk
	);

endmodule
