// sdm_mailbox.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module sdm_mailbox (
		input  wire        in_clk_clk,         //   in_clk.clk,          Clock Input
		input  wire        in_reset_reset,     // in_reset.reset,        Reset Input
		input  wire [3:0]  avmm_address,       //     avmm.address
		input  wire        avmm_write,         //         .write
		input  wire [31:0] avmm_writedata,     //         .writedata
		input  wire        avmm_read,          //         .read
		output wire [31:0] avmm_readdata,      //         .readdata
		output wire        avmm_readdatavalid, //         .readdatavalid
		output wire        avmm_waitrequest,   //         .waitrequest
		output wire        irq_irq             //      irq.irq
	);

	sdm_mailbox_altera_s10_mailbox_client_2200_6pvnrva #(
		.CMD_FIFO_DEPTH              (16),
		.CMD_USE_MEMORY_BLOCKS       (1),
		.RSP_FIFO_DEPTH              (16),
		.RSP_USE_MEMORY_BLOCKS       (1),
		.URG_FIFO_DEPTH              (4),
		.URG_USE_MEMORY_BLOCKS       (1),
		.DEBUG                       (0),
		.HAS_URGENT                  (0),
		.HAS_STATUS                  (1),
		.HAS_STREAM                  (0),
		.STREAM_WIDTH                (32),
		.HAS_OFFLOAD                 (0),
		.CRYPTO_MEMORY_TIMEOUT_VALUE (10000)
	) sdm_mailbox (
		.in_clk_clk         (in_clk_clk),         //   input,   width = 1,   in_clk.clk
		.in_reset_reset     (in_reset_reset),     //   input,   width = 1, in_reset.reset
		.avmm_address       (avmm_address),       //   input,   width = 4,     avmm.address
		.avmm_write         (avmm_write),         //   input,   width = 1,         .write
		.avmm_writedata     (avmm_writedata),     //   input,  width = 32,         .writedata
		.avmm_read          (avmm_read),          //   input,   width = 1,         .read
		.avmm_readdata      (avmm_readdata),      //  output,  width = 32,         .readdata
		.avmm_readdatavalid (avmm_readdatavalid), //  output,   width = 1,         .readdatavalid
		.avmm_waitrequest   (avmm_waitrequest),   //  output,   width = 1,         .waitrequest
		.irq_irq            (irq_irq)             //  output,   width = 1,      irq.irq
	);

endmodule
