// sdm_mailbox_altera_s10_mailbox_client_2200_6pvnrva.v

// This file was auto-generated from altera_s10_mailbox_client_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module sdm_mailbox_altera_s10_mailbox_client_2200_6pvnrva #(
		parameter CMD_FIFO_DEPTH              = 16,
		parameter CMD_USE_MEMORY_BLOCKS       = 1,
		parameter RSP_FIFO_DEPTH              = 16,
		parameter RSP_USE_MEMORY_BLOCKS       = 1,
		parameter URG_FIFO_DEPTH              = 4,
		parameter URG_USE_MEMORY_BLOCKS       = 1,
		parameter DEBUG                       = 0,
		parameter HAS_URGENT                  = 0,
		parameter HAS_STATUS                  = 1,
		parameter HAS_STREAM                  = 0,
		parameter STREAM_WIDTH                = 32,
		parameter HAS_OFFLOAD                 = 0,
		parameter CRYPTO_MEMORY_TIMEOUT_VALUE = 10000
	) (
		input  wire        in_clk_clk,         //   in_clk.clk,          Clock Input
		input  wire        in_reset_reset,     // in_reset.reset,        Reset Input
		input  wire [3:0]  avmm_address,       //     avmm.address
		input  wire        avmm_write,         //         .write
		input  wire [31:0] avmm_writedata,     //         .writedata
		input  wire        avmm_read,          //         .read
		output wire [31:0] avmm_readdata,      //         .readdata
		output wire        avmm_readdatavalid, //         .readdatavalid
		output wire        avmm_waitrequest,   //         .waitrequest
		output wire        irq_irq             //      irq.irq
	);

	wire         config_stream_endpoint_0_response_valid;         // config_stream_endpoint_0:response_valid -> s10_mailbox_client_inst:response_valid
	wire  [31:0] config_stream_endpoint_0_response_data;          // config_stream_endpoint_0:response_data -> s10_mailbox_client_inst:response_data
	wire         config_stream_endpoint_0_response_ready;         // s10_mailbox_client_inst:response_ready -> config_stream_endpoint_0:response_ready
	wire         config_stream_endpoint_0_response_startofpacket; // config_stream_endpoint_0:response_startofpacket -> s10_mailbox_client_inst:response_startofpacket
	wire         config_stream_endpoint_0_response_endofpacket;   // config_stream_endpoint_0:response_endofpacket -> s10_mailbox_client_inst:response_endofpacket
	wire         s10_mailbox_client_inst_command_valid;           // s10_mailbox_client_inst:command_valid -> config_stream_endpoint_0:command_valid
	wire  [31:0] s10_mailbox_client_inst_command_data;            // s10_mailbox_client_inst:command_data -> config_stream_endpoint_0:command_data
	wire         s10_mailbox_client_inst_command_ready;           // config_stream_endpoint_0:command_ready -> s10_mailbox_client_inst:command_ready
	wire         s10_mailbox_client_inst_command_startofpacket;   // s10_mailbox_client_inst:command_startofpacket -> config_stream_endpoint_0:command_startofpacket
	wire         s10_mailbox_client_inst_command_endofpacket;     // s10_mailbox_client_inst:command_endofpacket -> config_stream_endpoint_0:command_endofpacket
	wire         config_stream_endpoint_0_command_status_invalid; // config_stream_endpoint_0:command_invalid -> s10_mailbox_client_inst:command_invalid

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CMD_FIFO_DEPTH != 16)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cmd_fifo_depth_check ( .error(1'b1) );
		end
		if (CMD_USE_MEMORY_BLOCKS != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cmd_use_memory_blocks_check ( .error(1'b1) );
		end
		if (RSP_FIFO_DEPTH != 16)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					rsp_fifo_depth_check ( .error(1'b1) );
		end
		if (RSP_USE_MEMORY_BLOCKS != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					rsp_use_memory_blocks_check ( .error(1'b1) );
		end
		if (URG_FIFO_DEPTH != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					urg_fifo_depth_check ( .error(1'b1) );
		end
		if (URG_USE_MEMORY_BLOCKS != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					urg_use_memory_blocks_check ( .error(1'b1) );
		end
		if (DEBUG != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					debug_check ( .error(1'b1) );
		end
		if (HAS_URGENT != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					has_urgent_check ( .error(1'b1) );
		end
		if (HAS_STATUS != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					has_status_check ( .error(1'b1) );
		end
		if (HAS_STREAM != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					has_stream_check ( .error(1'b1) );
		end
		if (STREAM_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					stream_width_check ( .error(1'b1) );
		end
		if (HAS_OFFLOAD != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					has_offload_check ( .error(1'b1) );
		end
		if (CRYPTO_MEMORY_TIMEOUT_VALUE != 10000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					crypto_memory_timeout_value_check ( .error(1'b1) );
		end
	endgenerate

	altera_s10_mailbox_client_core #(
		.CMD_FIFO_DEPTH        (16),
		.CMD_USE_MEMORY_BLOCKS (1),
		.RSP_FIFO_DEPTH        (16),
		.RSP_USE_MEMORY_BLOCKS (1),
		.URG_FIFO_DEPTH        (4),
		.URG_USE_MEMORY_BLOCKS (1),
		.HAS_URGENT            (0),
		.HAS_STATUS            (1),
		.HAS_STREAM            (0),
		.STREAM_WIDTH          (32),
		.HAS_OFFLOAD           (0)
	) s10_mailbox_client_inst (
		.clk                               (in_clk_clk),                                                           //   input,   width = 1,            clk.clk
		.reset                             (in_reset_reset),                                                       //   input,   width = 1,          reset.reset
		.command_ready                     (s10_mailbox_client_inst_command_ready),                                //   input,   width = 1,        command.ready
		.command_valid                     (s10_mailbox_client_inst_command_valid),                                //  output,   width = 1,               .valid
		.command_data                      (s10_mailbox_client_inst_command_data),                                 //  output,  width = 32,               .data
		.command_startofpacket             (s10_mailbox_client_inst_command_startofpacket),                        //  output,   width = 1,               .startofpacket
		.command_endofpacket               (s10_mailbox_client_inst_command_endofpacket),                          //  output,   width = 1,               .endofpacket
		.response_ready                    (config_stream_endpoint_0_response_ready),                              //  output,   width = 1,       response.ready
		.response_valid                    (config_stream_endpoint_0_response_valid),                              //   input,   width = 1,               .valid
		.response_data                     (config_stream_endpoint_0_response_data),                               //   input,  width = 32,               .data
		.response_startofpacket            (config_stream_endpoint_0_response_startofpacket),                      //   input,   width = 1,               .startofpacket
		.response_endofpacket              (config_stream_endpoint_0_response_endofpacket),                        //   input,   width = 1,               .endofpacket
		.command_invalid                   (config_stream_endpoint_0_command_status_invalid),                      //   input,   width = 1, command_status.invalid
		.avmm_address                      (avmm_address),                                                         //   input,   width = 4,           avmm.address
		.avmm_write                        (avmm_write),                                                           //   input,   width = 1,               .write
		.avmm_writedata                    (avmm_writedata),                                                       //   input,  width = 32,               .writedata
		.avmm_read                         (avmm_read),                                                            //   input,   width = 1,               .read
		.avmm_readdata                     (avmm_readdata),                                                        //  output,  width = 32,               .readdata
		.avmm_readdatavalid                (avmm_readdatavalid),                                                   //  output,   width = 1,               .readdatavalid
		.avmm_waitrequest                  (avmm_waitrequest),                                                     //  output,   width = 1,               .waitrequest
		.irq                               (irq_irq),                                                              //  output,   width = 1,            irq.irq
		.axi_clk_in                        (1'b0),                                                                 // (terminated),                             
		.axi_reset_in                      (1'b0),                                                                 // (terminated),                             
		.urgent_ready                      (1'b0),                                                                 // (terminated),                             
		.urgent_valid                      (),                                                                     // (terminated),                             
		.urgent_data                       (),                                                                     // (terminated),                             
		.stream_ready                      (1'b0),                                                                 // (terminated),                             
		.stream_valid                      (),                                                                     // (terminated),                             
		.stream_data                       (),                                                                     // (terminated),                             
		.avst_stream_ready                 (),                                                                     // (terminated),                             
		.avst_stream_valid                 (1'b0),                                                                 // (terminated),                             
		.avst_stream_data                  (32'b00000000000000000000000000000000),                                 // (terminated),                             
		.stream_active                     (1'b0),                                                                 // (terminated),                             
		.crypto_error_recovery_in_progress (1'b0),                                                                 // (terminated),                             
		.crypto_memory_timeout             (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_awid            (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_awaddr          (32'b00000000000000000000000000000000),                                 // (terminated),                             
		.crypto_axi_target_awlen           (8'b00000000),                                                          // (terminated),                             
		.crypto_axi_target_awsize          (3'b000),                                                               // (terminated),                             
		.crypto_axi_target_awburst         (2'b00),                                                                // (terminated),                             
		.crypto_axi_target_awlock          (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_awcache         (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_awprot          (3'b000),                                                               // (terminated),                             
		.crypto_axi_target_awqos           (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_awvalid         (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_awuser          (5'b00000),                                                             // (terminated),                             
		.crypto_axi_target_awready         (),                                                                     // (terminated),                             
		.crypto_axi_target_wdata           (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated),                             
		.crypto_axi_target_wlast           (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_wready          (),                                                                     // (terminated),                             
		.crypto_axi_target_wvalid          (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_wstrb           (8'b00000000),                                                          // (terminated),                             
		.crypto_axi_target_bid             (),                                                                     // (terminated),                             
		.crypto_axi_target_bresp           (),                                                                     // (terminated),                             
		.crypto_axi_target_bvalid          (),                                                                     // (terminated),                             
		.crypto_axi_target_bready          (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_rdata           (),                                                                     // (terminated),                             
		.crypto_axi_target_rresp           (),                                                                     // (terminated),                             
		.crypto_axi_target_rlast           (),                                                                     // (terminated),                             
		.crypto_axi_target_rvalid          (),                                                                     // (terminated),                             
		.crypto_axi_target_rready          (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_arid            (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_araddr          (32'b00000000000000000000000000000000),                                 // (terminated),                             
		.crypto_axi_target_arlen           (8'b00000000),                                                          // (terminated),                             
		.crypto_axi_target_arsize          (3'b000),                                                               // (terminated),                             
		.crypto_axi_target_arburst         (2'b00),                                                                // (terminated),                             
		.crypto_axi_target_arlock          (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_arcache         (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_arprot          (3'b000),                                                               // (terminated),                             
		.crypto_axi_target_arqos           (4'b0000),                                                              // (terminated),                             
		.crypto_axi_target_arvalid         (1'b0),                                                                 // (terminated),                             
		.crypto_axi_target_aruser          (5'b00000),                                                             // (terminated),                             
		.crypto_axi_target_arready         (),                                                                     // (terminated),                             
		.crypto_axi_target_rid             (),                                                                     // (terminated),                             
		.axi_target_awid                   (),                                                                     // (terminated),                             
		.axi_target_awaddr                 (),                                                                     // (terminated),                             
		.axi_target_awlen                  (),                                                                     // (terminated),                             
		.axi_target_awsize                 (),                                                                     // (terminated),                             
		.axi_target_awburst                (),                                                                     // (terminated),                             
		.axi_target_awlock                 (),                                                                     // (terminated),                             
		.axi_target_awcache                (),                                                                     // (terminated),                             
		.axi_target_awprot                 (),                                                                     // (terminated),                             
		.axi_target_awqos                  (),                                                                     // (terminated),                             
		.axi_target_awvalid                (),                                                                     // (terminated),                             
		.axi_target_awuser                 (),                                                                     // (terminated),                             
		.axi_target_awready                (1'b0),                                                                 // (terminated),                             
		.axi_target_wdata                  (),                                                                     // (terminated),                             
		.axi_target_wlast                  (),                                                                     // (terminated),                             
		.axi_target_wready                 (1'b0),                                                                 // (terminated),                             
		.axi_target_wvalid                 (),                                                                     // (terminated),                             
		.axi_target_wstrb                  (),                                                                     // (terminated),                             
		.axi_target_bid                    (4'b0000),                                                              // (terminated),                             
		.axi_target_bresp                  (2'b00),                                                                // (terminated),                             
		.axi_target_bvalid                 (1'b0),                                                                 // (terminated),                             
		.axi_target_bready                 (),                                                                     // (terminated),                             
		.axi_target_rdata                  (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated),                             
		.axi_target_rresp                  (2'b00),                                                                // (terminated),                             
		.axi_target_rlast                  (1'b0),                                                                 // (terminated),                             
		.axi_target_rready                 (),                                                                     // (terminated),                             
		.axi_target_rvalid                 (1'b0),                                                                 // (terminated),                             
		.axi_target_arid                   (),                                                                     // (terminated),                             
		.axi_target_araddr                 (),                                                                     // (terminated),                             
		.axi_target_arlen                  (),                                                                     // (terminated),                             
		.axi_target_arsize                 (),                                                                     // (terminated),                             
		.axi_target_arburst                (),                                                                     // (terminated),                             
		.axi_target_arlock                 (),                                                                     // (terminated),                             
		.axi_target_arcache                (),                                                                     // (terminated),                             
		.axi_target_arprot                 (),                                                                     // (terminated),                             
		.axi_target_arqos                  (),                                                                     // (terminated),                             
		.axi_target_arvalid                (),                                                                     // (terminated),                             
		.axi_target_aruser                 (),                                                                     // (terminated),                             
		.axi_target_arready                (1'b0),                                                                 // (terminated),                             
		.axi_target_rid                    (4'b0000)                                                               // (terminated),                             
	);

	altera_config_stream_endpoint_wrapper #(
		.READY_LATENCY  (0),
		.HAS_URGENT     (0),
		.HAS_STATUS     (1),
		.HAS_STREAM     (0),
		.MAX_SIZE       (256),
		.STREAM_WIDTH   (32),
		.TYPE_NAME      (0),
		.INSTANCE_NAME  (0),
		.CLOCK_RATE_CLK (0)
	) config_stream_endpoint_0 (
		.clk                    (in_clk_clk),                                      //   input,   width = 1,            clk.clk
		.reset                  (in_reset_reset),                                  //   input,   width = 1,          reset.reset
		.command_ready          (s10_mailbox_client_inst_command_ready),           //  output,   width = 1,        command.ready
		.command_valid          (s10_mailbox_client_inst_command_valid),           //   input,   width = 1,               .valid
		.command_data           (s10_mailbox_client_inst_command_data),            //   input,  width = 32,               .data
		.command_startofpacket  (s10_mailbox_client_inst_command_startofpacket),   //   input,   width = 1,               .startofpacket
		.command_endofpacket    (s10_mailbox_client_inst_command_endofpacket),     //   input,   width = 1,               .endofpacket
		.command_invalid        (config_stream_endpoint_0_command_status_invalid), //  output,   width = 1, command_status.invalid
		.response_ready         (config_stream_endpoint_0_response_ready),         //   input,   width = 1,       response.ready
		.response_valid         (config_stream_endpoint_0_response_valid),         //  output,   width = 1,               .valid
		.response_data          (config_stream_endpoint_0_response_data),          //  output,  width = 32,               .data
		.response_startofpacket (config_stream_endpoint_0_response_startofpacket), //  output,   width = 1,               .startofpacket
		.response_endofpacket   (config_stream_endpoint_0_response_endofpacket),   //  output,   width = 1,               .endofpacket
		.urgent_ready           (),                                                // (terminated),                             
		.urgent_valid           (1'b0),                                            // (terminated),                             
		.urgent_data            (32'b00000000000000000000000000000000),            // (terminated),                             
		.stream_ready           (),                                                // (terminated),                             
		.stream_valid           (1'b0),                                            // (terminated),                             
		.stream_data            (32'b00000000000000000000000000000000),            // (terminated),                             
		.stream_active          ()                                                 // (terminated),                             
	);

endmodule
