// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4:1 MUX of 1 bit words.  Latency 1.  Select latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux4w1t1s1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [3:0] din,
    input [1:0] sel,
    output dout
);

wire [0:0] dout_w;
eth_f_mux4w1t0s1 mx0 (
    .clk(clk),
    .din(din),
    .sel(sel),
    .dout(dout_w)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

reg [0:0] dout_r = 1'b0;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ1nSJuP2+RkLk9XpgWjjHxepctPln4zPh6Wn55WVJqWucPeOun7T6LRy24oVAneroIZYUToYLQYTNB/sKUIwHTR/fU9LLAcWW3hp6h+H2OHn5sKWofcOY5uwhRVpMb4IgfDRtNmqw75Y5SzqZ/Eb7M8u9M3hY5akVSRQi4iQQAEjUd3h9nliaDcHbE5qPLB5XcZhpXk20DU/Of2BCxNzNb6Vx+3AAp778vrcLzK4kl3ygfK6HbN/uHxkjTub6f7fqgzRA7O5fG+Ro5YuEyl7bbiyscUObSRuMxXdy8+QiolSWokd3Qm5Yd75vMUfRseqA0HqbW12kc69hUnc/owDB1C92/j8om6Bjw4REb28ouujHy1XtapV9XayLDZQj/J/NrUkFRLxaOuF6RtVT6cSrUqrx3C83BNWQVNT9QQc801gydyrWobTdH/82qJ3t85fl9EiFIgLF5/hA9FYkgvsgA+IfBNeuy0aFoU1KYM39Va0xrj2OUDA+SCQou6JNkbovWvZ0FSuNjnK/wocTFLKiG9BSnvnSOr31p3DzaB/YWLASzyTq/+A+3BXP1z06SxgARdqdFC1oJbGqY9oDk7y2p1+VR1iLyeTbq2F9ZjrT+FH9OHXBw/GIkO3rjDdOLkFY8Y/Xj5JkMgTwzbX6bL9L6UFr9lkFst0EMI95Il7yJEgF1iPooXv6Jx7y6YqwjYF5xqmWAH7FL0Z5GVJZaKIYzm+IahvewWT2z/s80xsCN67LyR4CmdoWWc7hLO/OH5ZGmNUi1Ve/fs2O0meKJ0mY9H"
`endif