// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 2:1 MUX of 1 bit words.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux2w1t0s0 #(
    parameter SIM_EMULATE = 1'b0
) (
    input [1:0] din,
    input sel,
    output dout
);

generate
if (SIM_EMULATE) begin : g_sim_emulate
    assign dout = sel ? din[1] : din[0];

end else begin : g_sim_lut
    eth_f_lut6 lt0 (.din({1'b0,sel,2'b0,din}),.dout(dout));
    defparam lt0 .SIM_EMULATE = SIM_EMULATE;
    defparam lt0 .MASK = 64'hff00f0f0ccccaaaa;

end
endgenerate
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ0GPk6o1vNCVTZ6p+WWSjeW7Zpd4x9pasNcG/FTcemP0d4gehOLAozkTu9JSQpy1LnlYb7xxmGgtYfyJN11C9WPSYBcsRbiCL9dabF8WoC9CmnTq8IiWSW1a57lbb/AwBcb5peA/WK/HOtVCeG7QNy0kZAUGcTtv9b4glaYmLgZIIXFgLeXt52UAn+Hsqb2NfcoJqOhKlbZauzLi9csIWhtqo7UmmaU2bGb7qDzvu1JzhPq4gFbO2qjTCEQn/3VH5153QodJtZ2H1/+r9xKdK7vB0mX4wqsKeM+cfhIlULSnOd5hhONgjhTukhpWt5ptfjq1p1/R9shxWbwAiEAQH15m6Tpau28oZIL8Y8P514SD9Q7I3aW5GhdtFy/g2MLI7lnEBvOOBbXG4D8HTG3IHGoJkuUT9eq+ycEmOKkyB+4T+jR4s1mhCTNxytjKCXuJrki9dWCBn5O1t0IeIYwyTqqGAP9HBN22PwhSx+IyQfc4F3lZZncHS2vCg/MPPVJ8TpoCqhli4p6KdCoks/u1zch385rhxmM2+E8yGMJPBrK1HPoZ7+eZlScCSadJSmS4KHzvCWRRXi59Zn6lzuxJbxmjQenw8gujl8o0aDhwMIaO0V5JqT2bAxU+k4IBJsqu2I3O2XmHy+3ILHWiqMkwTp5aJzTe38GbKkREPaeubdQxM7x2Bsp0oFj+LEaMOZz3PTxnBivurx2NPzdo4fwtwUR8TqRMTn6avmdiNHQC2ORhnSvSOvFwomS7FoeUJWTZOfW1ASYdfsT/TWg67VqfbAd"
`endif