// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 2:1 MUX of 1 bit words.  Latency 0.  Select latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux2w1t0s1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [1:0] din,
    input sel,
    output dout
);

reg [0:0] sel_r = 1'b0 /* synthesis preserve */;
always @(posedge clk) sel_r <= sel;

eth_f_mux2w1t0s0 mx0 (
    .din(din),
    .sel(sel_r),
    .dout(dout)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3y1YOFVG4J+SFkJAX0qWIeTf2jx3YkzaE1vfpikf8jMgXnnEDk/qGmHP/pVPGfyDOk94neOE81046m/O0uLzsYeM20We/XMPPwUGpQJpEn2HpmELyv+TZJcQZCiX7rCuI/zDfig9nDK4Zc4vWpYjY6W6zpDze/MeG0vduJ7XJsEj5kx85eM3W+JdLBSpfKiz08sMu3nXYIrEGlvSToSQPr/TvN5+Y7SPwDDgB3oqnj/1jf1CepXdBPRdCYyyuoxDOwlkDpSC02vX0otXdQ8suUva/qkyWG9kzW++WVtV0WwRNyWBUlp4VLw2kYtovK0AfqZA79MFQerh9uJlAiDvt2y+TxzgxeyiGXh6JHY/CDYzp5ZjPxI/aNmVwTBR4eAyvtH7BkBhPqTSjDwxuCtLzkUET3/9inTbfM3jhe0sMfFgK9a6ScQkMkz51sWpDyDdkKZexEVcw5wkDZqNIog2lLbnAdvVStRSQg5CXkPudpYf9DUQqMTFnaNt8EA6KCexK6H1WOgAaE4OxFsB1LBK0iePqMar5uGVK7B/hAN3Dw0fmrjegd+vXX3dwxEL42xfCNrfpjCaJqYs1v32tpZ5sGr4JJnI4bkHPjf4x+XA04jCIxH3wffQLawLOzmm7n7KdQZMEmDlD71Z6IEa56eqllu2LRj1YTgahZA7R9QRmdpO4RrOt5qaMitVEQo3DKQnKzTCZrS9pHfqFy4J7PdtYU3azokBJb0nG/b8eOlZTjg4jHV8mekhe9f9GhdTspy74xBKjaHejjcReXZRHEGeIx"
`endif