// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 6 bit counter.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_cnt6 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    output [5:0] dout
);

wire [5:0] dout_w;

eth_f_lut6 t0 (
    .din({6'h0 | dout }),
    .dout(dout_w[0])
);
defparam t0 .MASK = 64'h5555555555555555;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

eth_f_lut6 t1 (
    .din({6'h0 | dout }),
    .dout(dout_w[1])
);
defparam t1 .MASK = 64'h6666666666666666;
defparam t1 .SIM_EMULATE = SIM_EMULATE;

eth_f_lut6 t2 (
    .din({6'h0 | dout }),
    .dout(dout_w[2])
);
defparam t2 .MASK = 64'h7878787878787878;
defparam t2 .SIM_EMULATE = SIM_EMULATE;

eth_f_lut6 t3 (
    .din({6'h0 | dout }),
    .dout(dout_w[3])
);
defparam t3 .MASK = 64'h7f807f807f807f80;
defparam t3 .SIM_EMULATE = SIM_EMULATE;

eth_f_lut6 t4 (
    .din({6'h0 | dout }),
    .dout(dout_w[4])
);
defparam t4 .MASK = 64'h7fff80007fff8000;
defparam t4 .SIM_EMULATE = SIM_EMULATE;

eth_f_lut6 t5 (
    .din({6'h0 | dout }),
    .dout(dout_w[5])
);
defparam t5 .MASK = 64'h7fffffff80000000;
defparam t5 .SIM_EMULATE = SIM_EMULATE;

reg [5:0] dout_r = 6'b0 /* synthesis preserve dont_replicate */;
always @(posedge clk)  dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ0ViShilgu4QxBMfY+yw9UZvXE3m3JIc3Wkdce2GuuKM/bXbYw3Dqn7d8ejpa6Ujyz0F7LqzdVGbvBPWzZjwqWCiukBwWNLiNsmL0ntEkLP+2wpfzypskWwGMPDEucXXYIkLpTP6fXktRjYsH4Dn0PSKESZEK2xJMc6RgJHogEa6ENdpyD/gFg3Cl1gpqbpHOqDT66FjnOg7I+GGMfNOj51TpDOGOCVIXX5oQZ2/IBhIqY9uF2e0Btq4PdZorLLoHk8rZ3yPICYqTtVNcAdiazJs/qMZEmNuEjQACDfGABQMZ7NidDQT5a8tl6DVSjOC7TYofW53saOqyYM9pUFkN0wj5E8zBpqUbqjVMY0mY5b8Y9yBmgAD5zSBslTiM0MlVzMIdAyCu+qiYkG6DAJulSdS98hsUqbO2Ykx/59cuAJn9o/kLXryYJTTcX7M03bjhimCpYHANYT1aI17BDKiTKfpPQo1OHsvKBK2UKrWfzam/GSbPr0b+mHawBoK6bo7WVBQrtOlLS3M2he5WjtiRDLIrwyqreL7COI7HJzfKiD4Zd7Yr4Cjj8Hx8++zYUzel50GL3S7iEGVitAUqSJlo0NfrEML9Vpl0KdBrXZcF5D7s0Z9aN5rxxs3zCgy39fhHmxThFwO5uGnK+t4n+snPEUpVBIkAh888BTrGu2TRw9wVFgS4Ms6cFjGH3bCo6Ea376S/LfW6N9V70blFAEbi/btGnWkUrDXiGfwEUbSAeJmbje8mf4ZQD5+p8yHOiOvh7rrsUA5eackFlgjBIe/6i6"
`endif