// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 19 bit val == const(4e1fb) equality comparator.  Latency 2.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc19h4e1fbt2 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [18:0] din,
    output dout
);

wire [3:0] leaf;

eth_f_eqc5h1bt1 cmp0 (
    .clk(clk),
    .din(din[4:0]),
    .dout(leaf[0])
);
defparam cmp0 .SIM_EMULATE = SIM_EMULATE;

eth_f_eqc5h0ft1 cmp1 (
    .clk(clk),
    .din(din[9:5]),
    .dout(leaf[1])
);
defparam cmp1 .SIM_EMULATE = SIM_EMULATE;

eth_f_eqc5h18t1 cmp2 (
    .clk(clk),
    .din(din[14:10]),
    .dout(leaf[2])
);
defparam cmp2 .SIM_EMULATE = SIM_EMULATE;

eth_f_eqc4h9t1 cmp3 (
    .clk(clk),
    .din(din[18:15]),
    .dout(leaf[3])
);
defparam cmp3 .SIM_EMULATE = SIM_EMULATE;

eth_f_and4t1 c4 (
    .clk(clk),
    .din(leaf),
    .dout(dout)
);
defparam c4 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ2IG89nu6NOJAQaQy2205/NPVFWeuzHZke/kLaOF9DxSWtzGrJ/va/TlHfqRs6+pk+HI636qHGgrXM0t1kFQmd3M0p7Fc90zsupVA36e9wHEylzKFnA9RxMD2WZgOWmA0GAVVgO0RXLC1aQDoa9C9rcllC6Ny38Qx571BWJ1c1TkBLAtTmEbrzrXvTC8Z6KWBsSxR7O3oNf45RzyOYmeAjhoVlnpd/q4zpxOHjqY8kgwz3lu9phuBFNJ6HKi4lwhQ5SZ0kN0M+RRO2r+k1JgriD8fpWozi+QmlanqVTGZQULYXDQLaHsCttrsj60Q1EgCUPN91N9ihpvYAa9R5Z+IknfjkxR9s44pxMsM8Sia111RbQnYt7wVDn+qq/vLnE5GljWGlqErKuiXYHaD14BEKUo0jXDpyCMMP0A40s7wCpvvbvRKqEJXcywf0MxXdB+5jwgJwMfUQKzSl7hWZh/0l/AO2ai/DCbA93kWjTGtBrrWLJOsQe+qZstw/77J+EYxY+nAZDQmA7P1LjB8dG3tflRTZXY+Wdir1h+10HPzU+jgC4FPnw55VXgxO4OrDt+pBGmG1obEfwcwJGODWIHwZmbxXqM89QofDtUG2TK4DJo67HKUl5hgMwovrFtZFUOfZfxB0SSKjaq7MbMVi6hB3YHyMVbonB15gNQF6ZVvXlVWdUlQ+5NZaoMqlLhivdwONCRiBwPMWYGAIjoiNiSUPXE35Dk3lv2hsSJ7LxyDkgH3LHG/nDoBfztBNX+8aRg3bpcgCZu6gR3nAW6SgZ8NOs"
`endif