// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 8:1 MUX of 1 bit words.  Latency 2.  Select latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux8w1t2s1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [7:0] din,
    input [2:0] sel,
    output dout
);

wire [1:0] head_din;
wire head_sel = sel[2];

eth_f_mux4w1t1s1 mx0 (
    .clk(clk),
    .din(din[3:0]),
    .sel(sel[1:0]),
    .dout(head_din[0:0])
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

eth_f_mux4w1t1s1 mx1 (
    .clk(clk),
    .din(din[7:4]),
    .sel(sel[1:0]),
    .dout(head_din[1:1])
);
defparam mx1 .SIM_EMULATE = SIM_EMULATE;

eth_f_mux2w1t1s2 mx2 (
    .clk(clk),
    .din(head_din),
    .sel(head_sel),
    .dout(dout)
);
defparam mx2 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ0dLzKiCNy9Hblka+yAfL8LUH3D/P6zYDLcFHNekXiFYWgFkVpcDvx7rFSjUmXfYd7tl8LEMgBV5UPGncYqmyYkSKoegEZwyG83EuwOXFXyatAi+Tln+wwqAB+MRuN5wlcKMuL2toiGogit9BPmARq6NwtJjQidRkHpwaRqyuhuQEyQaFuL/WRIU28N9i1Czqc4t6Wtp7Q41vSmvj2vt3sBzXiQM4GkUQ4zBoeFLMT8Ml38sYuW2PLbx285XxPt/1MCfAzlyMDoH0xmYxUV5ujk0odgDPmeYU+4JnPrXNnxORfVnW055Sb+5/kydvneeukOJtfNzhFTs5E9F/dajXN6vzHErl2aGd1JIMH87GTuc2cU9Mj+T6O1n6cN9GeyUejazIlRXKH3pnAzmIMyGVjJSYQ4TogxHGhIS+cVFphyn/amZN9pQLILVyBxUvLuwyjXaawli/WcCz7YevLGgdc1rTkOxCY7kNmPq1vKKTvur5qHEhV/9wubP3dpSR43eBvPjYcHDS2JwbTjWEgRC3jUfSJAjN3lxw0Pn7W7HqRzNTB0EEfXas0UBCOyXyDeitU4uJbPlJ0bvla138ynosOILbyNERRAnWFbM/uix0osT+LbNaxB9jf6V+JHLetIP5jKVp3XMcQNx/hB6OqJqm0Fa0ZsV/2NlOYXltavsnsL/cE6n1O4pVlsLyzrGfpDlhQcaYwUEEm9aQUFYtVs+cLN+P9KUJf3Z+SK0M/9Y9eCCK6WE6Hvjyq1RuiZkFGmPHrPTilqcZpTCZN2//A0LJ6/"
`endif