// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 3 input AND gate.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_and3t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [2:0] din,
    output dout
);

wire dout_w;
eth_f_and3t0 c0 (
    .din(din),
    .dout(dout_w)
);
defparam c0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r = 1'b0;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3fvL7V3g+aayNLtxuCoUqr3y7l/wydUrhIwLmagHEiCjU0pqPNeWe7jrfeQPd46NF/RBoUk47yuDoKM3DGl8UqxN8DoDtueN3kruTO1Lx7l1yaoQxTP/4X/oxxTaXklThhG2tLHLXU5LYf0uQsx6S/L51+9V+ap4pmXLIvT+FxPu+w2+dt4i0u4AG/eYi//MJTN/hSpVtk1oDKvFyHHNDNcPb3mC5HjCOj7RTfFYA42nuYx16n6LgdeI+jU4124JdNKZfaIoEVP5DJEy4gn9lVBEXSdvHbt7uYBSId4aEGCKJgV2qg+G+r1mtgQDH2TGoUo0IU9VVe2D+eiu+zH82B22rwnkuhDC+IQwaAsJKzOgH1t7zAyHs9nA6rxBxbtIjzRJAL+FdwHNiuCZAyF7+r84xGtAdchI5Hy3RD7XNzuGnvrmzalGtBHJVxin9oLZ1s2w4gPosp1OAOM3dHqGpnLDm+6sls44T0JcIHHasBQCZNdxvI68MhyjH6ki7qNGEeQq8wuCuevDetNP4BfyuKzrP96tk09Cx3mWHe/7fSXY3I7AAoaU0bPjVNGbz+A8N5tZiG6yZoSwHZKJbZ14awMm4jg99heWfu74ldcUB3ge98OLt49pVT5I4t3Pdyz7Ysy0VLI/dpC34lr8+JETmxSYu90mB6SDlmYWyNSpEx3TxM6KFvd/9F6ovk/xXrwQVzs5clxbx2dLAfumk+Zc3hKYkQ+1PdN/gLsuqqNB9JII3E9mmt+/dDCKpA+P4AHL3zvMON0c9zZLJd3nMua3WG"
`endif