// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 3 input AND gate.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_and3t0 #(
    parameter SIM_EMULATE = 1'b0
) (
    input [2:0] din,
    output dout
);

eth_f_lut6 t0 (.din({1'b1,1'b1,1'b1,din}),.dout(dout));
defparam t0 .SIM_EMULATE = SIM_EMULATE;
defparam t0 .MASK = 64'h8000000000000000;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ31I6/ughdkiccyUp2AfwpXJOEV4AnLUyGsF+zr+vcF24/cQN3grM/OPxcBA43HoRE65Q4vIbBHlXq/Wq8E5txmVj5O2wqR/q3AMPLgoajpDXnceFgU6RZCBIyBFtq0+cBgxp5FT1ZEAA86fRCvUqw4nYHX58+UXgitpdUoJI3rb3SK59lzRKErrBC4VAb+T3kc0N+ID3/+w3W5aoo4azqoo/k2c76oh8ApLS8FtcMW2x/x6GD7Yq1wcu0k4R6s+YWpOb1lBLDQoVtkz7MDp3dDejDmdfKRs7UdBrFGCeCD9Ns8l1ymOvDSc7HXp7z45WQhfR5Qt4rLkbVwvbjLA5mN4ynuqaKeTDoPFmzp4sPvg2JSbOpeFk1a0vaksMjtBu6qTqfqXYIFb8ZbMZScppfnJT5z5L1zuHjVoXmHr7huVvjXnbL1a9Eli45Ffj/Cw7kGD/EG+lvI+w4RPSpIhGH05hwFt4X6VpAjPTSKwEagxPG+h0uUO728SvkVspctN/auE4LRA/lBjcw7a9E87/f1gL9KajXYqKf8bXXYHhx6TKLEe4REiAJJ+pCWUDuDsAnl2+92wfbv3i52mButuVI5VTIFFVZKo+SB3YBACXPhw7uywVjYnBhNVpJZCUNINDWDwzQr4U+ijlb2r23x/ltrLYfysPW2oGRiEifIKimAGMZ2PJVcs3BnGGWE+C9Rlsw8+PSmhxqVQfZbnCuTvSKNmU6LoN4miGLehpzI9ThtGeKkr+6YtX7q22JZD+6QP+BZ2o9/nIiHxAfegPtHX6ri"
`endif