// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// Frequency monitor for 8 input signals.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_fmon8 #(
    parameter SIM_HURRY = 1'b0,
    parameter SIM_EMULATE = 1'b0
) (
	input clk, 
	input [7:0] din,
	input [2:0] din_sel,
	output [15:0] dout,
	output dout_fresh
);

////////////////////////////
// divide down and cross domain

wire [7:0] prescale;
wire [7:0] prescale_s;

genvar i;
generate
    for (i=0; i<8; i=i+1) begin : lp0
        wire [5:0] local_cnt;
        eth_f_cnt6 ct0 (
            .clk(din[i]),
            .dout(local_cnt)
        );
        defparam ct0 .SIM_EMULATE = SIM_EMULATE;

        assign prescale[i] = local_cnt[5];
        eth_f_sync1r1 sn0 (
            .din_clk(din[i]),
            .din(prescale[i]),
            .dout_clk(clk),
            .dout(prescale_s[i])
        );
        defparam sn0 .SIM_EMULATE = SIM_EMULATE;

    end
endgenerate

////////////////////////////
// select signal to watch

wire sel_prescale;
eth_f_mux8w1t2s1 mx0 (
    .clk(clk),
    .din(prescale_s),
    .sel(din_sel),
    .dout(sel_prescale)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

reg last_sel_prescale = 1'b0;
always @(posedge clk) last_sel_prescale <= sel_prescale;

reg ping = 1'b0;
always @(posedge clk) ping <= sel_prescale ^ last_sel_prescale;

////////////////////////////
// count selected signal

wire sclr;
eth_f_ripple16 rp0 (
    .clk(clk),
    .sclr(sclr),
    .inc(ping),
    .dout(dout)
);
defparam rp0 .SIM_EMULATE = SIM_EMULATE;

////////////////////////////
// regular measuring interval

generate
    if (SIM_HURRY) begin : g_sim_hurry
        // times 100 KHz
        eth_f_metronome32000 mt0 (
            .clk(clk),
            .sclr(1'b0),
            .dout(sclr)
        );
        defparam mt0 .SIM_EMULATE = SIM_EMULATE;

    end
    else begin : g_sim_normal
        // times 10 KHz
        eth_f_metronome320000 mt0 (
            .clk(clk),
            .sclr(1'b0),
            .dout(sclr)
        );
        defparam mt0 .SIM_EMULATE = SIM_EMULATE;

    end
endgenerate

assign dout_fresh = sclr;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ0PknZpq33mqclNUXKrAt1kJn7DnUEwFWj8Vwd1iPkBiXiAmmk4T18wXu3RRsiu6jDPWk2n14Bf75/fpCMzA+7txXD79ee/TPqnqs+4oum/ePHWIDGvG2mjQbAMkQgWDB9apkOiqD6xF/bewqMjL+0z4mkIiatgKNEfMrpRgvT4oTSCx97UVcOqkE6GjxyjXhv0wMlj/ab0y5vCr9+71p64iBUELNsxv7NNfSwFR3QsRrqc324A8ii7MlOPysfDVlJFPMwUmEZDE1f+/vnrF++IiiQTrS2X7BChYnl2RKsWk6TPHYD7l7cMTvkot+mRNjahH0Cv4urRXTlnvVdlCbMYtzE17FAPmvZ/tlM6FfYMQ+akFi8AYD8cwupBUdTFGkBo+gEE8LYiu7tbmwkp/zsVOmI2bZjCjW+dWn4PgU4vT8b9+k4zwUG2vexT8YZMCZG1Sf6DSZKuAj3oORyiVNCbDi++JVQt9/rdVSN1Xo3Cm5HyPLq8RmGvhUXzxc4Yy291sXfkwnNg5c/TD+B9eE4yMP4kmgEQNlXscg/lgEB+T4TSk3J2P2NLSyPhCPs8F4p8qskmWj6wjMZx+JWAPPfQOOw60jZDJsE50z/cqWO1meD7rrGYGORQdAIeNfxXzsNQdl4wlU22aK8awCnCXtTPlo8Mc+mXKoLliohcQ5Rt+Gt3HpFjJs64xav/YWc2usUaQQ+9/vr6xoB2f3saw+lZLZWC7Qbp9EwZ2J3cIhdIsZw3ArcN59m4qAmzaJjFlXrGC2ub8899FDXQyoij1F/X"
`endif