// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 5 bit val == const(7) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc5h07t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [4:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000000000080;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3B6jckm1PXghaOV4p2gF2KaqRec/3PQhFpZeAl0NOptGUU0jiQcb8ClVUcFeVHc6jz6fSNKStL2SNfKbDQzbXOsggukloMjK4Gqbw7Ae1JA5AkfIAVmm5cz3h9FWq2jTUPsN35WIxzOn+Puyvjg4zXt3WMIhjpRV5GI6IMU95iGIenmjvMTy+76brdLrFD3UNBotjIxqDcb5QRRsK/WRxuwM9mVBTROyKzag+bdNdR0FGUItF0JAL+WVrNdjtBoqrN0aW00trlDB4/a79WDXhn5/QNi7zmy8UToWRq1QQGPV+b0w9R/pwYgzqruGwita2kmoIwEMCkaPzt7wQPH1cgVZprG4nucSl1kMk82WiaFISCMGuhKmR7NWAfDrCxA53Ip99jxl6Gq0twmIfL/tZ3IOvd1bDq/SvCTxgTUwDoWSZjiBno1iD68rLMhb406p06FCgxT3/eIlvJjYrdK7dPSytG3CtwI8rQzXYe2q5/MFLqabM/frMSdxcVUioK16R/8wrhqwJMx7aCf8I5XmCwhqEf6pCX13egzD29t5VQDV4iYi72bDWrFk+QH0zNXTDzXf54KVXJYE7DO6BuNWc/1xW0zljfVbcBKfeLO/b5+kFKr9NkAnMFdleb1GTFTLh19Q0ldolDCaT7g+/uuH7Fo/hU3TNNSdwUJ0Z4Gfp4Z65oF1XRBuoUEIdKH1Miz1UnBptCphuy19gH16/G1ZRNrCk+0aZ15BKPdzWiyUIuBFUp5L7q3/w9c2qhRVE1KYxN7Ra8ZcOZoqP/mHVs1bR3"
`endif