// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4 input AND gate.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_and4t0 #(
    parameter SIM_EMULATE = 1'b0
) (
    input [3:0] din,
    output dout
);

eth_f_lut6 t0 (.din({1'b1,1'b1,din}),.dout(dout));
defparam t0 .SIM_EMULATE = SIM_EMULATE;
defparam t0 .MASK = 64'h8000000000000000;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ12OtFF5p4UQA+FbCNG3pUV7Fw4GQ3Xz4Vqy6lGGODBnM0KG8SHYYnjyNDncD6wNNJWCbVAZprp5TLPshv98/fWE3yuUtmvXZo4rc4UuUusuA/zeqr0nJ4CKN1uCSr3g43YaX35Fex4aKRItv/j2v6SPm7pms+GPCCbP6IYRhquNAURnrzhAXHuRHeVFu1Zhjt9bYeeXaiUSpGWK8UoyzHq01e/XMeVEyPWf6Pgv+shX+b7irkSKo+pGOFFa0tHR8HgH1B9rndBxI4uO5lR69JEuzGfkLnKynr1heLfwvlWJfRINdL7lsuTEtYcv+A8ezFYvwy2Sg2YZzQi+Gcs+cEqfd++tfAd91VANflBdtE5+EByfLJu/+xrFfdSerPb76UU6IihEf39hBESIoInW9COi8RxtvxI9L5a5Sj026Sc02RhtnO55q1dRmr0ZrEMKxKHJyWENaDNh38VkdEcv4+wEGHWXnmia5nlVVEifz+QwfqY7IrGlb9uoUM4hzXKsXgUbMCuGJPKVSfFWTQbgE+YDOGauzPr8gN//EXgVZ40ov5jFaUA0N+ByHkF34Flrgf670rFDhKoRqB11F1e7qd6noMYTL7de7u7lm1l3P7sQLOoIjvZEAKW1COh8P8zQRFkfyFwzJPj4ZOptlv9G2eznyqUnr+Fh9tsuzVLg6OOcBD7MGW3rkJ7ubS5U6xDBl8Y/Kv1zTnshtKGN1EH42pM8X3Ljl0AAK0B/NBBQ+Y8vu0lpa9pYm1ABzJu0+kpg2GLlQsqNjZjP4CkhyTvKhmM"
`endif