// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 2:1 MUX of 1 bit words.  Latency 0.  Select latency 2.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux2w1t0s2 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [1:0] din,
    input sel,
    output dout
);

reg [0:0] sel_r = 1'b0 /* synthesis preserve */;
always @(posedge clk) sel_r <= sel;

eth_f_mux2w1t0s1 mx0 (
    .clk(clk),
    .din(din),
    .sel(sel_r),
    .dout(dout)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ0dDCD7KAs7U2HK7CDjdNJPEZTg/OFOMhhERJPujB8bEQgJG0pHfMqQ2vN49UN/5G2x37U0GfgyLmYOC+MbfJMcrw3dz9Q2p/1+87DJtjfvcYSxyLGzWZFJV9WQS4tn/0/T0sIN6193YoeWOk/9c0PpZL/4axrk9C2pCpn67oNAjwVrzOB3sU3cG9nbktpXwBZezv8ZSVOk1AMznVPyNXCcl66zIhTzqhS0Nb6SFNGEGFLVY8D4n23b07lwLRvP2LkTwjTOgxItDUlrjn8CStB8ddlNF8i0ToW2uz3AvtKuPwxP7TD9MCngv/bnJe6yn/SSOgTESoxHwgey9D+G3Z3rX9Yj9Rqhp2+5xQQ10BW3UiPGMGV4Z0U9t2eCRHiRs3HH24QKzDY+Wg9orLxsS9tFfAdRewW0r8mjSzWv9ZkWf/durhoccGnvYAiYhWBn/ibCEcFy3s1mEwCAkydNu9izh5YADfH3c6MPWXFpqaW86618CYYcguxWoRdcBmpVkdyALjr5QnjAs1ZJs18f/JQhYO7o4RSisMrNqemFgklCulkE5t8Q7Ubd8Fk8w5/B3hXAnLUe20m7tK022SNLW94Mpcd/G3GfJPel0zjZrTieFugMdSWtA0UHf0qlE4Cg/siqMKlMNytDQu65r/OR/hO8BKSklvm4wYhXPfQvL0gnc9LpaJbZPARGh+xmcwLxSIwcS0hZvf4J1aGzk5atN1HQRO26JedxJNuE7mJZG5RqwLgdZzKG9yIabirSA/+fpH7yn4eR5prAuORJhhR3KMW9"
`endif