// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Copyright 2010-2019 Altera Corporation. All rights reserved.
// Altera products are protected under numerous U.S. and foreign patents, 
// maskwork rights, copyrights and other intellectual property laws.  
//
// This reference design file, and your use thereof, is subject to and governed
// by the terms and conditions of the applicable Altera Reference Design 
// License Agreement (either as signed by you or found at www.altera.com).  By
// using this reference design file, you indicate your acceptance of such terms
// and conditions between you and Altera Corporation.  In the event that you do
// not agree with such terms and conditions, you may not use the reference 
// design file and please promptly destroy any copies you have made.
//
// This reference design file is being provided on an "as-is" basis and as an 
// accommodation and therefore all warranties, representations or guarantees of 
// any kind (whether express, implied or statutory) including, without 
// limitation, warranties of merchantability, non-infringement, or fitness for
// a particular purpose, are specifically disclaimed.  By making this reference
// design file available, Altera expressly does not recommend, suggest or 
// require that this reference design file be used in combination with any 
// other product not provided by Altera.
/////////////////////////////////////////////////////////////////////////////

`timescale 1ps/1ps

// Generated by one of Gregg's toys.   Share And Enjoy.
// Executable compiled May 18 2018 10:06:40
// This file was generated 08/16/2019 14:20:21

module intc_mlab6_a1r1w1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input wclk,
    input [0:0] waddr,
    input [5:0] din,
    input rclk,
    input [0:0] raddr,
    output [5:0] dout
);

wire [5:0] dout_i;

////////////////////////////////////////
// handle data bits 5..0

reg [0:0] waddr_m0 = 1'b0 /* synthesis preserve_syn_only */;
always @(posedge wclk) waddr_m0 <= waddr;

reg [5:0] wdata_m0 = 6'b0 /* synthesis preserve_syn_only */;
always @(posedge wclk) wdata_m0 <= din[5:0];

reg [0:0] raddr_m0 = 1'b0 /* synthesis preserve_syn_only */;
always @(posedge rclk) raddr_m0 <= raddr;

intc_mlab m0 (
	.wclk(wclk),
	.wena(1'b1),
	.waddr_reg(waddr_m0),
	.wdata_reg(wdata_m0),
	.raddr(raddr_m0),
	.rdata(dout_i[5:0])
);
defparam m0 .WIDTH = 6;
defparam m0 .ADDR_WIDTH = 1;
defparam m0 .SIM_EMULATE = SIM_EMULATE;

////////////////////////////////////////
// handle output connection

assign dout = dout_i;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ36bHo6EU9KdTxflK+/DO5hfC/DFf3k9sk925W5uBGcwT7ZfgQNR8TfsOV+4QAnyRJ/GFFLm9pvHvKLdETmCQIcp77wpwqweLcaNhnfL59LlUY5QF09gTvzyiBDQm8iAILYau86H22i9n9Nvh3crkBiSpTP9UXmYwWZI2xakQ23J6pXJDzGoCa1NiNaZ7dHNdXH4SnMLv/uf1ePvB5rrHkbZ2RxOFgvFp1RSXWr7XRVFzz8J/L9UUgC5mbtdumvt/gKpjA18lWFtVeRSJuybVv4o2Slu5uRNbh9SUV6hZ29f5igXb/znghz0Zs5iw21VhtxfDL9BB7OCaKiWiEjT8OCp8q1PUU3sPTs04c7HDKhaD0Gh2ilP0duxS0po7TkZpXm/B3jY4Qnu2FqxapctYCF2csJeA3THJk0AWa4haxtfAC9J1EpLKibMqndg9K7MGKrT/ZEvgWRY9dOpJ8UaJxddDEoLyMELMJ7w3XLfpkk3iCUlom2k2UV0QzxwF+IMD4komijccP5R0JgDDYLYv+Ju4FJQ17DufKeNhH/Icml6gkZWP/L4Wy8Y/fJHHK1FaxAw2QhO9jCEsmBbc/UOu6DBUmEpooJsd9Rbo4k+bPrYpg08XFcpap/hUMKLz1kNNFAEqacayWOGdgvoeVkkWTybLbo308+9lwQxzV6nQJ7ur4wLGxs4qpo4Sjm+XN7R3C6qZkcZ4nFYxNXmZj7mPpXf5u6/xGy4Jp5We7fzUfbx14sjPwlyFjmyF4oAQRvpkdXb0/aBv/izy+Z1vAAhZfL"
`endif