// ftile_systempll_ref4.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module ftile_systempll_ref4 (
		output wire  out_systempll_synthlock_2, // out_systempll_synthlock_2.out_systempll_synthlock
		output wire  out_systempll_clk_2,       //       out_systempll_clk_2.clk
		output wire  out_refclk_fgt_2,          //          out_refclk_fgt_2.clk
		output wire  out_refclk_fgt_3,          //          out_refclk_fgt_3.clk
		output wire  out_refclk_fgt_4,          //          out_refclk_fgt_4.clk
		output wire  out_refclk_fgt_5,          //          out_refclk_fgt_5.clk
		input  wire  in_refclk_fgt_2,           //                refclk_fgt.in_refclk_fgt_2
		input  wire  in_refclk_fgt_3,           //                          .in_refclk_fgt_3
		input  wire  in_refclk_fgt_4,           //                          .in_refclk_fgt_4
		input  wire  in_refclk_fgt_5,           //                          .in_refclk_fgt_5
		output wire  out_coreclk_2,             //             out_coreclk_2.clk
		output wire  out_coreclk_3,             //             out_coreclk_3.clk
		output wire  out_coreclk_4,             //             out_coreclk_4.clk
		output wire  out_coreclk_5,             //             out_coreclk_5.clk
		input  wire  disable_refclk_monitor_2,  //  disable_refclk_monitor_2.disable_refclk_monitor_2
		input  wire  disable_refclk_monitor_3,  //  disable_refclk_monitor_3.disable_refclk_monitor_3
		input  wire  disable_refclk_monitor_4,  //  disable_refclk_monitor_4.disable_refclk_monitor_4
		input  wire  disable_refclk_monitor_5   //  disable_refclk_monitor_5.disable_refclk_monitor_5
	);

	ftile_systempll_ref4_systemclk_f_400_v3lqleq #(
		.refclk_fgt_always_active_0    (1),
		.refclk_fgt_always_active_1    (1),
		.refclk_fgt_always_active_2    (1),
		.refclk_fgt_always_active_3    (1),
		.refclk_fgt_always_active_4    (1),
		.refclk_fgt_always_active_5    (1),
		.refclk_fgt_always_active_6    (1),
		.refclk_fgt_always_active_7    (1),
		.refclk_fgt_always_active_8    (1),
		.refclk_fgt_always_active_9    (1),
		.enables_systempll             (4),
		.systempll_refsrc_0            (4),
		.systempll_refsrc_1            (4),
		.systempll_refsrc_2            (4),
		.enables_refclk_fgt            (60),
		.enables_coreclk_fgt           (60),
		.refclk_fgt_freq_0             (0),
		.refclk_fgt_freq_1             (0),
		.refclk_fgt_freq_2             (156250000),
		.refclk_fgt_freq_3             (156250000),
		.refclk_fgt_freq_4             (156250000),
		.refclk_fgt_freq_5             (156250000),
		.refclk_fgt_freq_6             (0),
		.refclk_fgt_freq_7             (0),
		.refclk_fgt_freq_8             (0),
		.refclk_fgt_freq_9             (0),
		.enables_cdrout_fgt            (0),
		.enables_refclk_fht            (0),
		.enables_commonpll             (0),
		.commonpll_refsrc_0            (0),
		.commonpll_refsrc_1            (0),
		.syspll_availpor_0             (1),
		.syspll_availpor_1             (1),
		.syspll_availpor_2             (1),
		.refclkready_enable            (1),
		.systempll_c0_counter_0        (""),
		.systempll_c1_counter_0        (""),
		.systempll_c2_counter_0        (""),
		.systempll_c0_output_enable_0  (""),
		.systempll_c1_output_enable_0  (""),
		.systempll_c2_output_enable_0  (""),
		.systempll_f_out_c0_hz_0       (""),
		.systempll_f_out_c1_hz_0       (""),
		.systempll_f_out_c2_hz_0       (""),
		.systempll_f_pfd_hz_0          (""),
		.systempll_f_ref_hz_0          (""),
		.systempll_f_vco_hz_0          (""),
		.systempll_fractional_enable_0 (""),
		.systempll_m_counter_0         (""),
		.systempll_n_counter_0         (""),
		.systempll_ethernet_preset_0   (""),
		.systempll_pcie_preset_0       (""),
		.systempll_eth_flux_used_0     (""),
		.systempll_c0_counter_1        (""),
		.systempll_c1_counter_1        (""),
		.systempll_c2_counter_1        (""),
		.systempll_c0_output_enable_1  (""),
		.systempll_c1_output_enable_1  (""),
		.systempll_c2_output_enable_1  (""),
		.systempll_f_out_c0_hz_1       (""),
		.systempll_f_out_c1_hz_1       (""),
		.systempll_f_out_c2_hz_1       (""),
		.systempll_f_pfd_hz_1          (""),
		.systempll_f_ref_hz_1          (""),
		.systempll_f_vco_hz_1          (""),
		.systempll_fractional_enable_1 (""),
		.systempll_m_counter_1         (""),
		.systempll_n_counter_1         (""),
		.systempll_ethernet_preset_1   (""),
		.systempll_pcie_preset_1       (""),
		.systempll_eth_flux_used_1     (""),
		.systempll_c0_counter_2        ("__BB_DONT_CARE__"),
		.systempll_c1_counter_2        ("__BB_DONT_CARE__"),
		.systempll_c2_counter_2        ("__BB_DONT_CARE__"),
		.systempll_c0_output_enable_2  ("__BB_DONT_CARE__"),
		.systempll_c1_output_enable_2  ("__BB_DONT_CARE__"),
		.systempll_c2_output_enable_2  ("__BB_DONT_CARE__"),
		.systempll_f_out_c0_hz_2       ("__BB_DONT_CARE__"),
		.systempll_f_out_c1_hz_2       ("__BB_DONT_CARE__"),
		.systempll_f_out_c2_hz_2       ("__BB_DONT_CARE__"),
		.systempll_f_pfd_hz_2          ("78125000"),
		.systempll_f_ref_hz_2          ("__BB_DONT_CARE__"),
		.systempll_f_vco_hz_2          ("__BB_DONT_CARE__"),
		.systempll_fractional_enable_2 ("__BB_DONT_CARE__"),
		.systempll_m_counter_2         ("__BB_DONT_CARE__"),
		.systempll_n_counter_2         ("__BB_DONT_CARE__"),
		.systempll_ethernet_preset_2   ("ETHERNET_FREQ_830_156"),
		.systempll_pcie_preset_2       ("PCIE_UNUSED"),
		.systempll_eth_flux_used_2     ("__BB_DONT_CARE__"),
		.cmnpll_xtensa_used_0          (""),
		.cmnpll_xtensa_used_1          (""),
		.cmnpll_en_cmos_refclk_out     (""),
		.fhtref_fref_hz_0              (""),
		.fhtref_fref_hz_1              (""),
		.silicon_revision              ("10nm7agdrb"),
		.device_revision               ("10nm7agdrb")
	) systemclk_f_0 (
		.out_systempll_synthlock_2      (out_systempll_synthlock_2), //  output,  width = 1, out_systempll_synthlock_2.out_systempll_synthlock
		.out_systempll_clk_2            (out_systempll_clk_2),       //  output,  width = 1,       out_systempll_clk_2.clk
		.out_refclk_fgt_2               (out_refclk_fgt_2),          //  output,  width = 1,          out_refclk_fgt_2.clk
		.out_refclk_fgt_3               (out_refclk_fgt_3),          //  output,  width = 1,          out_refclk_fgt_3.clk
		.out_refclk_fgt_4               (out_refclk_fgt_4),          //  output,  width = 1,          out_refclk_fgt_4.clk
		.out_refclk_fgt_5               (out_refclk_fgt_5),          //  output,  width = 1,          out_refclk_fgt_5.clk
		.in_refclk_fgt_2                (in_refclk_fgt_2),           //   input,  width = 1,                refclk_fgt.in_refclk_fgt_2
		.in_refclk_fgt_3                (in_refclk_fgt_3),           //   input,  width = 1,                          .in_refclk_fgt_3
		.in_refclk_fgt_4                (in_refclk_fgt_4),           //   input,  width = 1,                          .in_refclk_fgt_4
		.in_refclk_fgt_5                (in_refclk_fgt_5),           //   input,  width = 1,                          .in_refclk_fgt_5
		.out_coreclk_2                  (out_coreclk_2),             //  output,  width = 1,             out_coreclk_2.clk
		.out_coreclk_3                  (out_coreclk_3),             //  output,  width = 1,             out_coreclk_3.clk
		.out_coreclk_4                  (out_coreclk_4),             //  output,  width = 1,             out_coreclk_4.clk
		.out_coreclk_5                  (out_coreclk_5),             //  output,  width = 1,             out_coreclk_5.clk
		.disable_refclk_monitor_2       (disable_refclk_monitor_2),  //   input,  width = 1,  disable_refclk_monitor_2.disable_refclk_monitor_2
		.disable_refclk_monitor_3       (disable_refclk_monitor_3),  //   input,  width = 1,  disable_refclk_monitor_3.disable_refclk_monitor_3
		.disable_refclk_monitor_4       (disable_refclk_monitor_4),  //   input,  width = 1,  disable_refclk_monitor_4.disable_refclk_monitor_4
		.disable_refclk_monitor_5       (disable_refclk_monitor_5),  //   input,  width = 1,  disable_refclk_monitor_5.disable_refclk_monitor_5
		.out_systempll_synthlock_0      (),                          // (terminated),                                       
		.out_systempll_synthlock_1      (),                          // (terminated),                                       
		.all_qhip_in_rst                (),                          // (terminated),                                       
		.src_rst_done                   (),                          // (terminated),                                       
		.rst_src_n                      (1'b1),                      // (terminated),                                       
		.ftile_reconfig_active          (1'b0),                      // (terminated),                                       
		.out_systempll_disconnect_0     (),                          // (terminated),                                       
		.out_systempll_disconnect_1     (),                          // (terminated),                                       
		.out_systempll_disconnect_2     (),                          // (terminated),                                       
		.out_systempll_status_0         (),                          // (terminated),                                       
		.out_systempll_status_1         (),                          // (terminated),                                       
		.out_systempll_status_2         (),                          // (terminated),                                       
		.out_systempll_clk_0            (),                          // (terminated),                                       
		.out_systempll_clk_1            (),                          // (terminated),                                       
		.out_refclk_fgt_0               (),                          // (terminated),                                       
		.out_refclk_fgt_1               (),                          // (terminated),                                       
		.out_refclk_fgt_6               (),                          // (terminated),                                       
		.out_refclk_fgt_7               (),                          // (terminated),                                       
		.out_refclk_fgt_8               (),                          // (terminated),                                       
		.out_refclk_fgt_9               (),                          // (terminated),                                       
		.in_refclk_fgt_0                (1'b0),                      // (terminated),                                       
		.in_refclk_fgt_1                (1'b0),                      // (terminated),                                       
		.in_refclk_fgt_6                (1'b0),                      // (terminated),                                       
		.in_refclk_fgt_7                (1'b0),                      // (terminated),                                       
		.in_refclk_fgt_8                (1'b0),                      // (terminated),                                       
		.in_refclk_fgt_9                (1'b0),                      // (terminated),                                       
		.avmm_clk                       (1'b0),                      // (terminated),                                       
		.avmm_reset                     (1'b0),                      // (terminated),                                       
		.refclock_ready                 (3'b000),                    // (terminated),                                       
		.refclock_status                (),                          // (terminated),                                       
		.in_refclk_fht_0                (1'b0),                      // (terminated),                                       
		.in_refclk_fht_1                (1'b0),                      // (terminated),                                       
		.out_fht_cmmpll_clk_0           (),                          // (terminated),                                       
		.out_fht_cmmpll_clk_1           (),                          // (terminated),                                       
		.in_cdrclk_0                    (1'b0),                      // (terminated),                                       
		.in_cdrclk_1                    (1'b0),                      // (terminated),                                       
		.out_cdrclk_0                   (),                          // (terminated),                                       
		.out_cdrclk_1                   (),                          // (terminated),                                       
		.out_coreclk_0                  (),                          // (terminated),                                       
		.out_coreclk_1                  (),                          // (terminated),                                       
		.out_coreclk_6                  (),                          // (terminated),                                       
		.out_coreclk_7                  (),                          // (terminated),                                       
		.out_coreclk_8                  (),                          // (terminated),                                       
		.out_coreclk_9                  (),                          // (terminated),                                       
		.en_refclk_fgt_0                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_1                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_2                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_3                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_4                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_5                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_6                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_7                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_8                (1'b0),                      // (terminated),                                       
		.en_refclk_fgt_9                (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_0       (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_1       (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_6       (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_7       (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_8       (1'b0),                      // (terminated),                                       
		.disable_refclk_monitor_9       (1'b0),                      // (terminated),                                       
		.enable_syspll_watchdog_timer   (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_0 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_1 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_2 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_3 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_4 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_5 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_6 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_7 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_8 (1'b0),                      // (terminated),                                       
		.enable_refclk_watchdog_timer_9 (1'b0),                      // (terminated),                                       
		.refclk_fgt_enabled_0           (),                          // (terminated),                                       
		.refclk_fgt_enabled_1           (),                          // (terminated),                                       
		.refclk_fgt_enabled_2           (),                          // (terminated),                                       
		.refclk_fgt_enabled_3           (),                          // (terminated),                                       
		.refclk_fgt_enabled_4           (),                          // (terminated),                                       
		.refclk_fgt_enabled_5           (),                          // (terminated),                                       
		.refclk_fgt_enabled_6           (),                          // (terminated),                                       
		.refclk_fgt_enabled_7           (),                          // (terminated),                                       
		.refclk_fgt_enabled_8           (),                          // (terminated),                                       
		.refclk_fgt_enabled_9           ()                           // (terminated),                                       
	);

endmodule
