// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// This is an auto-generated file. Do not edit this file.
// altera_config_stream_endpoint.sv

`timescale 1 ns / 1 ns

package altera_config_stream_endpoint_wpackage;

function integer nonzero;
input integer value;
begin
	nonzero = (value > 0) ? value : 1;
end
endfunction

endpackage

module altera_config_stream_endpoint_wrapper
    import altera_config_stream_endpoint_wpackage::nonzero;
#(
    parameter READY_LATENCY          = 0,
    parameter HAS_URGENT             = 0,
    parameter HAS_STATUS             = 0,
    parameter HAS_STREAM             = 0,
    parameter MAX_SIZE               = 256,
    parameter STREAM_WIDTH           = 64,
    parameter TYPE_NAME              = 0,
    parameter INSTANCE_NAME          = 0,
    parameter CLOCK_RATE_CLK         = 0
) (
    input         clk,
    input         reset,
    output        command_ready,
    input         command_valid,
    input  [32-1:0] command_data,
    input         command_startofpacket,
    input         command_endofpacket,
    output        command_invalid,
    input         response_ready,
    output        response_valid,
    output [32-1:0] response_data,
    output        response_startofpacket,
    output        response_endofpacket,
    output        urgent_ready,
    input         urgent_valid,
    input  [32-1:0] urgent_data,
    output        stream_ready,
    input         stream_valid,
    input  [STREAM_WIDTH-1:0] stream_data,
    output        stream_active
);

	altera_config_stream_endpoint #(
        .READY_LATENCY          (READY_LATENCY),
        .HAS_URGENT             (HAS_URGENT),
        .HAS_STATUS             (HAS_STATUS),
        .HAS_STREAM             (HAS_STREAM),
        .MAX_SIZE               (MAX_SIZE),
        .STREAM_WIDTH           (STREAM_WIDTH),
        .TYPE_NAME              (TYPE_NAME),
        .INSTANCE_NAME          (INSTANCE_NAME),
        .CLOCK_RATE_CLK         (CLOCK_RATE_CLK)
) inst (
        .clk                    (clk),
        .reset                  (reset),
        .command_ready          (command_ready),
        .command_valid          (command_valid),
        .command_data           (command_data),
        .command_startofpacket  (command_startofpacket),
        .command_endofpacket    (command_endofpacket),
        .command_invalid        (command_invalid),
        .response_ready         (response_ready),
        .response_valid         (response_valid),
        .response_data          (response_data),
        .response_startofpacket (response_startofpacket),
        .response_endofpacket   (response_endofpacket),
        .urgent_ready           (urgent_ready),
        .urgent_valid           (urgent_valid),
        .urgent_data            (urgent_data),
        .stream_ready           (stream_ready),
        .stream_valid           (stream_valid),
        .stream_data            (stream_data),
        .stream_active          (stream_active)
	
	);

endmodule

// synthesis translate_off
// Empty module definition to allow simulation compilation.
module altera_config_stream_endpoint
    import altera_config_stream_endpoint_wpackage::nonzero;
#(
    parameter READY_LATENCY          = 0,
    parameter HAS_URGENT             = 0,
    parameter HAS_STATUS             = 0,
    parameter HAS_STREAM             = 0,
    parameter MAX_SIZE               = 256,
    parameter STREAM_WIDTH           = 64,
    parameter TYPE_NAME              = 0,
    parameter INSTANCE_NAME          = 0,
    parameter CLOCK_RATE_CLK         = 0
) (
    input         clk,
    input         reset,
    output        command_ready,
    input         command_valid,
    input  [32-1:0] command_data,
    input         command_startofpacket,
    input         command_endofpacket,
    output        command_invalid,
    input         response_ready,
    output        response_valid,
    output [32-1:0] response_data,
    output        response_startofpacket,
    output        response_endofpacket,
    output        urgent_ready,
    input         urgent_valid,
    input  [32-1:0] urgent_data,
    output        stream_ready,
    input         stream_valid,
    input  [STREAM_WIDTH-1:0] stream_data,
    output        stream_active
);
	
	//for simulation, assign all outputs to zero
	assign command_ready 			= '0;
	assign command_invalid 			= '0;
	assign response_valid 			= '0;
	assign response_data 			= '0;
	assign response_startofpacket 	= '0;
	assign response_endofpacket 	= '0;
	assign urgent_ready 			= '0;
	assign stream_ready 			= '0;
	assign stream_active 			= '0;

endmodule
// synthesis translate_on

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "KaCcZ9W53ZG+KOUC3MpOxTkG8JzVU+FMIR8JyDs33NK1wcErIABMqJM+BlBnaEf20FCKJ7ToOlAha/ltC5u0ZbClu2TybZQciMInF+iFoiagt+B91BK4dyi6GJUCXUDuBK9YH6nNlwSkR01tHuzzS5ZEiJtw78iQaS7cFEmJNjv/muideRZVdy13EnGEeyFpK62Cg4KcVOZTCHinGABXbAtq/uBBjPG6GClkBmeTng0TuiLBvCy2kxJ3Z5j98zSA7pv83UbldcP8iT1GzHT9ij//iDT4JS/TrWwdKqGWGh3w58mZHPYoTZgof6XtnmvDpGfAH7BoCqshMRzcbWykWlrGjr3SY+XWDlGS7qawL9LM/GMq3Hzp7D7CFbDMpyrcdAHXVkR/jlSDYbXRzJvRVt2WduPqz1f8LhYZZ41XNsOJWp6k1+NPM26K3IHveNhiz4/2GyNaKIRwpSZ0n6I6nkE9mFkHIRPPQN5zyiYDoPtalZIcvarYj4QCKcESk43jqWoqIGVkWe5OXXHPpakiAEJrIX7+b/G+fAuQWvia7BV7wJTioPbICK0TMNnXzqlPpqFxefI8I9MhBdCTNZIWelaUI1CPSB5va0+8nTrShuIo6IduI2mQZEvXHkDN6H78H8i2WzCx9hW8vlLkO9G/FYlb0vYZN3qQ2HclhDnpdXW+D5tg+Fd1aBP09WRfEi7LzJZzHg6l0IGa7v7RDmEV+W3XDuY/QGqIoODMPMb0iIzj/CIFeEpesg9lszJpwrqic7BsyzjfhmwFK3VLWC21jvnxRiV8Gq9uPIhuR5fKJyvGKcprF9HGBaGxgtpyyeCucO4ehhg7I8ZhS63L54gqs7QBxa4tWY1bABolpWUdQE2XAXjIVKJJqx5lwDTODlALkpWtw0SFyoreEilglwi3OQTS9eMyDol/Xlw7SMnndQPflyrQz3UQeLaxrA5i12oV7eOAPOemCXLd25eW8+sAtCbbKzLqbmiOiysPUXHcJZ3jyYx1BjtVy92d/RErZS2z"
`endif