// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Copyright 2014 Altera Corporation. All rights reserved.
// Altera products are protected under numerous U.S. and foreign patents, 
// maskwork rights, copyrights and other intellectual property laws.  
//
// This reference design file, and your use thereof, is subject to and governed
// by the terms and conditions of the applicable Altera Reference Design 
// License Agreement (either as signed by you or found at www.altera.com).  By
// using this reference design file, you indicate your acceptance of such terms
// and conditions between you and Altera Corporation.  In the event that you do
// not agree with such terms and conditions, you may not use the reference 
// design file and please promptly destroy any copies you have made.
//
// This reference design file is being provided on an "as-is" basis and as an 
// accommodation and therefore all warranties, representations or guarantees of 
// any kind (whether express, implied or statutory) including, without 
// limitation, warranties of merchantability, non-infringement, or fitness for
// a particular purpose, are specifically disclaimed.  By making this reference
// design file available, Altera expressly does not recommend, suggest or 
// require that this reference design file be used in combination with any 
// other product not provided by Altera.
/////////////////////////////////////////////////////////////////////////////


`timescale 1ps/1ps

// DESCRIPTION
// Register based synchronizer of width 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_sync1r1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input din_clk,
    input [0:0] din,
    input dout_clk,
    output [0:0] dout
);

// set of handy SDC constraints
localparam MULTI_2 = "-name SDC_STATEMENT \"set_multicycle_path -to [get_keepers *eth_f_sync1r1*ff_meta\[*\]] 2\" ";
localparam MULTI_3 = "-name SDC_STATEMENT \"set_multicycle_path -to [get_keepers *eth_f_sync1r1*ff_meta\[*\]] 3\" ";
localparam FPATH = "-name SDC_STATEMENT \"set_false_path -to [get_keepers *eth_f_sync1r1*ff_meta\[*\]]\" ";
localparam FHOLD = "-name SDC_STATEMENT \"set_false_path -hold -to [get_keepers *eth_f_sync1r1*ff_meta\[*\]]\" ";

reg [0:0] ff_launch = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge din_clk) begin
	ff_launch <= din;
end

localparam SDC = FPATH;
(* altera_attribute = SDC *)
reg [0:0] ff_meta = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge dout_clk) begin
	ff_meta <= ff_launch;
end

reg [0:0] ff_sync = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge dout_clk) begin
	ff_sync <= ff_meta;
end

assign dout = ff_sync;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ2htu4HnxItElLJkLgr091P0xfBeY4rCyynAw1+S30ZXNsLqrJJSIqongjHWLdV9UIBlAYQLVghkFmOrA4wCVGfhFi0Rs5BpO3zGmt/g3r92OiYO26WwMcHAADo4rGBRYrLAzB/CkoRlhRmh01B5NegqfBNoflMJflPdrmDMMcF+fspdtYFn2EZDYX0YO+jKtDx/ux+zKequMlkk1jEBZXB/6ySRk5iC9SWGw5OodVvUTmlCg0BpprZtgBMvOlQP/k2EIfjrlbJ4zgzFzy749ZIBtcOVAhV+jr83UTAIQXW8t52N0fbof0o5CcgVAmSLtyrZGfP4J4S1cvkv+ADFAd3jSkcz5ZlPuwlclpccvHIRNy65Np68Diy+EZw1caxyFao29iWsS+4o3bvmaTX/3mDbfvcWXtXdzQfmH+Vakv49jmVaBg6uLgxUsMPWjsDmyRngvW1UCTHJ6cQxUnKFH/AaSTkU/MxfCRMTKvurfF1AhwAY+9Rzjcr6+HBrjENDxhEf++9zALK5lKAnS+ma4V92AbG6Ey2HRult64TwZzTtTdSrx4eQ+k9CjRFQNQXg1AZyVI2mITYCbDCPQyEC/WmWlRxrIPwLpfr0uiBrbFVS7sxiPJq31JzyPErkwg02pfzYiVcY9xUenh2tljesjWzlzt7wdKOJICMibjHKzHxC0wk8v75scuj+2nGBzYLsKvOm9yQ2kgv3D11IJ+L+A1hyzCruCrGOT54UgOf7tOuSiZk1WiUOrD/poyiFLXa/BHwFkSyWw6Mz1IC6xkXtCa6"
`endif