// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 5 bit val == const(1b) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc5h1bt1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [4:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000008000000;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ03Y1mgl4/Y16li0dWKjQLD7jdwHg8JxqroBOxALdOUnhXT3mrRGOtnj0wSkG9nxepOeDPNH9c0GX/5xp6E+GqKmmiZEden5JXo24S067/h+69Fvd1g4BllLNliH7WYSlmcm7fNzQRAdN/Ags58NHYN63Shzy3hjt+AtfY53RfA+T5QV0CSgDAIdI3h70CQC9sjpWbHBPwZ02RUi4zIfEfc5JWUn8LSVOhSS2mZF/OlQ8PXcFnGNVte4GaofF1RJ0NyOalFIhgicIeF+axguxcKngK4k5vVurXn5FnInItIo4Ov9XkbDVj78eZEPq18Dmatg59RwSUvgqHF1h3KvcXXBhVb52q7P2VbRAAkzlrAHSRfKl40eqNXvMlw7m/ajGzdh5j6x/Pn//Vb4+7dOryBnMfq1PSYxnFUHZISCFwZppFhH5gr7Hdp/2lTt6fxAfAL/HN+cCh+dRC+dogRCrw+TUH8+Ajrxnupq2HG3NCQMM2F7jBLq2CFHFjUs6hGxcrSk7BR+OGnejM4MCHNU7Zyw8zH1AJIQsXFZW+1fvvwf0alPKso14fT98cVohg0c+bhcrYz4J2OnHq+kfufmRDCZtoDe7o5I+I3WwwIL8nHA8J5alhdkSlVCi9x86RdeqI8Z30t/KnxxZJa7pXG2CmPr2HMzwUBbt9NR1LNlLHJ9nyGhqGjuTA0jIOH9CblSl/98K3EJ23yUerD/SoAPYCoyOEPU91k2wedFKM0JkNfAJNH+X0K8+O+lRPgYggTyvDfbgSH3kUpyfw8bwDTFQpY"
`endif