// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 5 bit val == const(f) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc5h0ft1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [4:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000000008000;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ33zCcVS20mkaHoeOYEYDVRAtAoHLdYO+TqsicFGQBUjk6DH0bIR+gKGSYstcfAbiakpOOBtDq5kPsMkDkuqEOkLbqc0DlBIp2keZDAy/OckcAYY8GaUNqrRYX9kwZtQaB3cf52HR2SXtgjN+TjxLm2Z9g7Vhy0UhjxYhuArWYaGDdRuEeerriHCIqH6385ejCmB6Irav0j1Qqd3zSQ3MgsmTyWKbHfjHzZO5ldDWFS1ESaL1pde+nbzgESykb72NQOjTtubUG4ajGtB0pyY5HK8hmGmGURTWjmaZUlx1ooFYnJfc+uWCrcLglUGWRkMRQ4TWSC5qiBLqWAmCTaZAnor/ZW5VkC9uuipPuC/sSwgzCUGVzbt1xH6gVQe4C0NX1xdxx3+/V9UJTvDVTsgsQLRnnGp6ZNRkYxzaoIe6EsUF9cJmBZbuyHo1Dm28hoeNP1gP8xT55+HGp26O5hoysvrfe+FRaFdj6JmqDevLw6FG3XwStGwsGIcRzOY5aeuh9EEd/ZXW8HzvuRDiNAHI0aOpP3U2w9Ht66BScZ11Zt8FrspXfOIQlmzj39+IDtwzmJJ0Yc+Vc6iB/IOh21IoI4E2DvEd8vdPb8wlgJnGKMEWsW3oK3KLZCOrsbWCqOLpvcgsPS+Hh+ufjYvbvGMHGECM/nDzREc4D+vGkVIZn0gZzVJlUozk+PGzCevVI/gzEPBIugSvZKO8Q296FKw7xTkbnPgIO+icJGlR9fTGQgMzj3B4lQBhxVgZBPZZhUgktsq5IcDwagYr3ocS+K7tfN"
`endif