// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4 input AND gate.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_and4t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [3:0] din,
    output dout
);

wire dout_w;
eth_f_and4t0 c0 (
    .din(din),
    .dout(dout_w)
);
defparam c0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r = 1'b0;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3EIhzOe2y4gLTAjoEHve0DdavoynuWbuBzmeGe7kVXuHxR3l2iFHj/MGYBiVtsTRal7gZnwOSaZ32k2YqPZ/zCGNT23Y+p+j6DSdY+OHisBPwsV1SFSdw8jp4ymdKw4lS78Hd2LN6THKrZT6L1/999EB/BnrZxjpTYpCIMR2shZ8y1PPL3HQrax1LhSoBN23Wk9APh0jBN3ai2OU3K1skR7IMy52+xRM5mDEpzeziEELZg6HxTcQDK4uaZXKg7bVYLzqUyljs9itRZGMPrcwCfyexh1P1IDzAmq3DwbEYJQ8nED4BXO+vGmcu4m0m0E1HdonqPZI8053Nu0z1yp337vYUpo3Kw8L5PHIqjddwT4B92B9RQOVsSCtYdHn/RFD3BOVHV2fFOcl0zFeK8WB+Z6wvZeo/9J9DI+ZXpXjCmhMWNen3D9qfiYu6mj8wQnD5CMHu8rFQUER9CGTQ7lPZ3M0qd7M+1XjxoRC8AAFa6EP43l3FZ9u0BLGFbxYNdPFuthwUla6TpVc6bKnRIuXXG1SvYLM7iCcmG13MDXjEiqmiv22J92GmnTljRjDf2id6fZ9LbFdol6dbQ6dOSV5RbZ1P/KOJHUK3MK662JKLOkuxxBTBogoS034Zr6tWrrPu0Jtf9T1mcFr+ZqKfgiGxjRZ8//pHFWW4HCfldmvWZ54LEPPRm5P23fX5+gjvwzUHSqHfp+3gGM9J7mJpG30HqaNr0h0gbGnXnxFDi1u+qAcbkuSqES2LeKExiK0wrHKdEl46F8yUhDjb1u3iCD1rR"
`endif