// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4:1 MUX of 1 bit words.  Latency 0.  Select latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux4w1t0s1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [3:0] din,
    input [1:0] sel,
    output dout
);

reg [1:0] sel_r = 2'b0 /* synthesis preserve */;
always @(posedge clk) sel_r <= sel;

eth_f_mux4w1t0s0 mx0 (
    .din(din),
    .sel(sel_r),
    .dout(dout)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ1LzaDs7ZH7vn0f2D/9CloIZFJJ0H+KGYkatI+WyDSSrOgJCOtWMRLNe8qlrP+OD3co5akLQy2xBbfhLy97fSkOnPYCbAUrs80mypksawafYygj/HEEqUkMBIG0884oQc4j1SahG0GWzMQqsw0X9uGQ60PBZHYJxPFWg4RHJt/HEMQnKilOSAktrizM5ywV/TIaraOfpGkAUVRy1HrE5GuXt1tz/mt8hlHKbpukLIC6gJOTIN2nidX76gslyc/4jY0CSrNNt2P88uk9ARp/aNc3sOzKuAl5ql0RbLOl5NLJJg89CFTLWju0lFnnMTYJZ0/+jutDQf+ZEFy6XpDy2uOCsxA4sUf6vUBIevymD2ungi6OTd/Qj0MUC6t/071QiMTSjwNz7G2CtQeJAcS+skxuu27SKt/Keln9oflB52Zn1Szki1EjfGXLoPHVNJHG9y28Lp2paSZt7o00AqpGCXBpTXiVJ1OLN0PUyxSlfXSLJWEiUe/So64rFns2/LLDdKxKix/B5B/k09vDigeqtL89CfZhqh8Blamq6LOi0iuVoUPqEJxNqSQEEbNS+hKhYOEfLzIlDXtdUbrFYC0Ylc7832oH6mXZUEmGDiLPa0WDOTDK7a7MeuZmXSRT/CiH2eRRCSqk2G1po/ofHfB/Cyf0cvUVxkegPmOgz7rcnPsiWvx0cH6MhgfnVJRnSII3fmFsl3oYxHno/vtpZT0Z7Nj+hlB1cDgBZFfXEQio8u0dJFE4PpbgmhvvhcYfIIK5wIJasaQhkXFYkTTnCWUsKSV4"
`endif