// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 15 bit val == const(7cfb) equality comparator.  Latency 2.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc15h7cfbt2 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [14:0] din,
    output dout
);

wire [2:0] leaf;

eth_f_eqc5h1bt1 cmp0 (
    .clk(clk),
    .din(din[4:0]),
    .dout(leaf[0])
);
defparam cmp0 .SIM_EMULATE = SIM_EMULATE;

eth_f_eqc5h07t1 cmp1 (
    .clk(clk),
    .din(din[9:5]),
    .dout(leaf[1])
);
defparam cmp1 .SIM_EMULATE = SIM_EMULATE;

eth_f_eqc5h1ft1 cmp2 (
    .clk(clk),
    .din(din[14:10]),
    .dout(leaf[2])
);
defparam cmp2 .SIM_EMULATE = SIM_EMULATE;

eth_f_and3t1 c3 (
    .clk(clk),
    .din(leaf),
    .dout(dout)
);
defparam c3 .SIM_EMULATE = SIM_EMULATE;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3iPHQTFNwpDSNYtDLhTbBPp4QtKKbTBpfqNval1ktjiXsCgw6SInnxPgG0hGJ3uZneap2PXP7re/GjwCRuoaN5iNFOPzmihDoU/w9hJHp/CWyCxa/jdg8fQa1lrJL9BkqwIn70JTBcdJf46igs0/L0OGHDB9rZRM2DcEgglZCkOaS7Pg53zWkg8iGHIowrTWnYYW3X1AByy4W1Tyg8CRCXJ+VnjF1M2mxB7ZcD2bQ6f89dY0tOI9ZlfaHLBU2aKZKVcGsWNEzrbwMiO/m0yaOYYr5Hpe7t0m7kB+gb0BZSYgn9/oqV1NSgs3JnV4vlwJThvlzN5AJh9AJdyH6mbQZrhMhF6QlDiMYttNQzTXopVrK5ESo7yUSITzmaHDWYVcdx7Y9VMObFEhFS1NUr+QbqtHJA4udGZ3NshyIP8vTYS1A/eT+nHGpMcbzOIGXBZNVRNGSR0QvAK2F97jtmcEz63jt2Pjq68t3q3bUVfGTg3P69P60dPRgay48CywZKoNevtA0RbEZoPoCW+e4ISz/wbSSW7ggI9MZ/gpo098N7YhbtwtkR9u8gfJmOsCH0+z6jjLcTWDXUc6+iASZSvkgIwF9TeS/SFW6xKMZ/LHmS8oL38Xt4XD8llLV0cpP+aHxyIeiMKnlB481XcCq4tytgQMGVFy3/TtuhMnccyCQ4QCNLOxZCHEqW0tPsW1hvbIps+FzqUSxrtZ+6B3dKDi5FDfFtvDAYsywIHuE3MH9EP0nPk6Samn6pL/O273u2dKSx5n9Z68oXGXjGJivK7VDq"
`endif