// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 2:1 MUX of 1 bit words.  Latency 1.  Select latency 2.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux2w1t1s2 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [1:0] din,
    input sel,
    output dout
);

wire [0:0] dout_w;
eth_f_mux2w1t0s2 mx0 (
    .clk(clk),
    .din(din),
    .sel(sel),
    .dout(dout_w)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

reg [0:0] dout_r = 1'b0;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ2cFTU7t5RaampcpMlibR+vvjCGm0/bCdHZXqS5b9s6phWIx50Pf5ocIUo6ZBd4PAo4I7dZ/J5J7ztwLRrDG4F9v0VDNhly/VsVaYhxMTRJhxjXSYL0ux3WgYBp2F8mdWbmzli9jtkc3VDb9Edczg4enUMOqQC4VPnHCve1cR7i6v8M4L5paD+2zxanOrNVyDZ6LYHM9rxa8Bh1A2mqaz0QeVSDkRJSUOyhIpY0fhEBA/flZkxZZPRZUyL6Ea/VNRj+MgXprOMmRSvvCkSJWZ2ecaDo/H5gBnK9jzDXjwJ8U3spUq46GF7gU1Gpx36MHnxcQghdogoDGpvoOlAZRc2+BWsjQlF/Xy9JSime9LlkZNJCO/TBhm9w2zp6Xc/IwGBd8YqrdZ8Bo4ODIdwZWQ6T5cBTql6zyksoi+iutLk+fEnESBxFwtcvGVbBy5VznG0GW6Zu2Ap4ybz6vlwrJaUpIc0x5DXnYsZcYm3/ZecGQHFRCG8KGwoOCf+BKTk5rMzLgreQHZq8Z3BcZDH0tAhdcbIQ2DawCTJd1l7kMlNiX5s4UMGEIGiGJhrZSGOT32VFRh7SqIrqQYzmo1QSYUgltWhfsrLxVGS1q6mLrvTWere1lVG56IFKXRWeDImY1k9cvM4plgCwzoFK5in/eLeGGhITGkbWLFAhJA4hqW5LG1zbIDt1afdBuvLcSM+uKoquAplcQ8gM7rfZiNQtMIXksJEb90TN+J+NtyfzkZR2h2hz6C17+Stg5p/YriiU/hgM4phk0uV4TiKcWP9kVewe"
`endif