// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 5 bit val == const(18) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc5h18t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [4:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000001000000;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3imiesG6R1vCPE3nAP5OiMSzQwn9gxEkUd8tFiv+DcPnV80arpODsPP/zpGEZ4BqTbDWEVymU2ohnGsvQn2Nvs533lplxOcoNiX5tmuOlpiE912Twd8lZSkklT6BP7d4mzZ1t2+typtlSBwaqnl18phh/2rj5yZB2bCMVFBZS+iQKa9grkBN7Tgq3yCeSO82oopYxRQ7JG9Jrm2OZ9Q3qFnPfcXqYcBLyub4RKR1IsbcdvOQF2bQ5j+bBGTegIV+k1P5kXOSMwgEMYsR8OrGHN2l/66SIIVXBDJHmMeh0F5FEC3SnfXq8BGNixfeVJhf8CP2ArW8nlSqxQC8wtt6l5PL0aju4uMiQcgzmtLVXRcj2QSQIy2Jip2fkGKjkbAGttIlq0BxPooiCnOP9l2zrGXStFTGR15+mO5RVzFA1zZdqW0MIdODTORONNaXIwMDoilHL16lrlwKzFsJUYm9mo/ZX9FHK6S4kmz/Du4k528J7RHOaXPEYe7BkaggeQy9LtcWV8aS/GBwrw85f0imjr4gZIecfx+QnSjqA0N5zI4rQAbf3wSiJY3SRYeAvscdseRi6BpH/io5fjjcANYXer1UTrFHBOZctT+MYi3ngON0jjvXLLoZxPIvgvRAQMT2KMxujau2RRby7JKG6X9kF8UoyIxrZqlzGcRL2UexNQ3i8UQFP0Pw/LAHykzn4bYMcgVFtYdcqoBvmuDZDINWKygLVAse1uVI23zTU6k6KaNS3InnbOIzPkNk2KYl0djRklJNzOurPzrUqTTg+vmtm5"
`endif