// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4 bit val == const(9) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc4h9t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [3:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000000000200;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ2AH7kg8kVgbEs2RCd+L0tCr6SwsMRxvn1ep/xU6XjQyp1E25XJWmmnkrKHPTLVPoPl+xhOsS59XtEG8KEQ92qSixyjf36q26MgNQRtCrkG83tzWpLxlXr1DuYGrRBDqhGaLePPqXhO5uXRjpIrAO3T6UELzJkIhvniGlwl/YEOJnfKvFSm4eHHSHUFxXPV09DDGXDtmPcSPCD5lgQ+vgWEKGIHQCfPIk0Xekogj45ox/fA3EBvo5ouuJeQPOMYIjz1AH4oIR3qlGdPXnkUz1U5o6U2NXAYFgOOjVRWNJ9ama6Z/4Perf4+qfEKa/xRqaht1QsdCv+Nxb4F2JHw6UYy0FN2R062ibL6c9CpLDuEHfOYOWrtBaESDalFgJCqW6p+GCwNKtzj3fxZQA2+c/15OoYLOmwtAOncKgKIeeB5gMHufwSvnyKiNlM8ExIS76lsMLCzWXmeWl7SuMgT+qBiH2nPdYs7NKZG8P6tMPlJ/3s1/zNp2geV0U6NrOzc4eCad38UTP8YWysFpcrIdGCE8UpcHABj7PG08gzORbXnMqnf7sefkyjSLxJ0q/MnmxymitGBcDXZAZxO30dO84ExeF/7rY2fqQjOjSfELAvdM1C7pq9F7sbrDY5BfdZ7brQ2V7L5Ml2X/pHdDp4CI9rw9NIMRgAnPzK7kiOXxoa3nZLSggxTR6tI+Qx7dOFk0B6oVOvbUeSPXqf1nYYnI54NBkJMNKR1teO5u4U1wqAdVtvdyc7yEFp/07zROhZbepwzpAJPp9CEev9EDXTjwcOz"
`endif