// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 4:1 MUX of 1 bit words.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux4w1t0s0 #(
    parameter SIM_EMULATE = 1'b0
) (
    input [3:0] din,
    input [1:0] sel,
    output dout
);

eth_f_lut6 lt0 (.din({sel,din}),.dout(dout));
defparam lt0 .SIM_EMULATE = SIM_EMULATE;
defparam lt0 .MASK = 64'hff00f0f0ccccaaaa;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3nehtC/nqGOvYwTSSD0t0GKs0ezd+oOfn+si6oEfrlhGcvvWYND6MGto/zIYAx+1Tprh8dGtY5ibSzAt32BI7t1eJwZAnxJ2+x2/zLU0ss6+f1ACzBiD51qjwoXffKzN6cdGY0qIVjNZUy1OdacPt1stZF4auML9B5PPKjTS7vrCurIy23DRVq8FWw0VkuunSei2Sk/FxeJoTbZfQCm4pNudRJu1X00NSjVk1QlMto22We57pbLfApmxXZveH0Ep0p+f6Tp7U3dFjOitSndmTLnQZtcYjUvVhYZ4kerMpIcDWqrM77SgDzZVemD3KF0lubZpDf9ScrnxOL5lARAS1hti6JYgdpRYK3ukuuOmcJTFN+0uJWl8Y0p9vY86ishYi3Q+meSk+yYTJsMFDyX/YeTLkTXloEXXRaEFUKozFUZX5D7uKHxDjflCOwkrqJUzn0tuOAsXyFjJu72t2Ok2CifxXPfRhqpisUCRDCHWV3/5LpFDgtwtj455gHUyHrDe6spsrW31olviruQAhoWC6jKPNAEuCYnny2cUtzlJ274Q/83zuBj2ZOMP0SN0ui3n1V3pChbxiDf+657ryy+FLfg+dJvlq/ynCWxX4af14gUHExtGd/geNOHLWqCNf8vtKu6ZDWnbkfvnLOPBS0iBnSoMCMDch+jPfooXFOIXJjdAF6RYnqvvAUz7VW1nPsJ448TiLOkGcydTOV601f7ScK4tJWrfZ9GpCFxBFCTIvhCuhDq70gk6pxAYB5EQoUYnsu4ccF31mvAbdtkFf8RZHW"
`endif