// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 5 bit val == const(1f) equality comparator.  Latency 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_eqc5h1ft1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [4:0] din,
    output dout
);

wire dout_w;

eth_f_lut6 t0 (.din(6'h0 | din),.dout(dout_w));
defparam t0 .MASK = 64'h0000000080000000;
defparam t0 .SIM_EMULATE = SIM_EMULATE;

reg dout_r0 = 1'b0;
always @(posedge clk) dout_r0 <= dout_w;

assign dout = dout_r0;
endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3Pf5XeEfaL/s7CZeIv/R6bItjmKXo9Tw0jz6Ihp3Xr/8/WsJusgEn+rPHQvzL7Up0RcMcYrCVprqkFRfzgjBcFzz5wGt4yODp1dFjdyfGY0uS44kvl8mN/sswFNWFW5d3Dg6XvWpW2SvU2Lq/v6m0pyaHUDl/uA8JIS8dmAreXez2EiRqMNisF8VtYnuGeqnv7UgRSq8OjMf3ncsEhk14pbBBcsM4TiFgYdTytRchLsLp61p35aJRQmX/1vLDSpTMNBayMYqTXx8O1J9WSXzAWFCD7PDfdKLJfOOXMF+1CFQBdJgWl8QwzVdW89hIy6tzT0rouniahbEp32Kh1T+yWeBNWv81n3PCM3Iu4c1JbnYLYp2IunChfFlpSzXeuSicrIo4jtpAsB5lS81iTYchzj1wD4DrsVn1oHw3yhOVmuYP9tea4Te0v2g20XD9AGkNdYzeEeM9DmUMq3n7i3Rb6N659lzVUyliQyNVC8awBQCO2rqMi+80UsD0B+Kxh7vRYF74advd7RiWw/F5Xxxwfp10+aMbqSswJeBILSQoGvTkCxfxA78KgC2jZS1eX03DJhLgbCA69wCamXaMvmHcFRvyndqwJnQiroRT0Iunf1d0PfTd34UV+NabiSOQkt0u9REcdzdhM8oR1FXEpkp6HbF6rit/Oa4g6J37NQZ4FK5SISAgh9w3B44xxrOdamwElSoBiGmizOr1GLVP59ldU5aOcnNxjoXxwLHlrdEqhYKBPFIjj44ftOfHvjIh6nQu2Hkg/6GlJ/Kkm6rMhda3c"
`endif