// (C) 2001-2025 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License Subscription 
// Agreement, Altera IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Copyright 2010-2019 Altera Corporation. All rights reserved.
// Altera products are protected under numerous U.S. and foreign patents, 
// maskwork rights, copyrights and other intellectual property laws.  
//
// This reference design file, and your use thereof, is subject to and governed
// by the terms and conditions of the applicable Altera Reference Design 
// License Agreement (either as signed by you or found at www.altera.com).  By
// using this reference design file, you indicate your acceptance of such terms
// and conditions between you and Altera Corporation.  In the event that you do
// not agree with such terms and conditions, you may not use the reference 
// design file and please promptly destroy any copies you have made.
//
// This reference design file is being provided on an "as-is" basis and as an 
// accommodation and therefore all warranties, representations or guarantees of 
// any kind (whether express, implied or statutory) including, without 
// limitation, warranties of merchantability, non-infringement, or fitness for
// a particular purpose, are specifically disclaimed.  By making this reference
// design file available, Altera expressly does not recommend, suggest or 
// require that this reference design file be used in combination with any 
// other product not provided by Altera.
/////////////////////////////////////////////////////////////////////////////

`timescale 1ps/1ps

// Generated by one of Gregg's toys.   Share And Enjoy.
// Executable compiled May 18 2018 10:06:40
// This file was generated 08/16/2019 14:20:21

module intc_sync6_m #(
    parameter SIM_EMULATE = 1'b0
) (
    input din_clk,
    input [5:0] din,
    input dout_clk,
    output [5:0] dout
);

wire [5:0] dout_w;
intc_mlab6_a1r1w1 m0 (
    .rclk(dout_clk),
    .wclk(din_clk),
    .waddr(1'b0),
    .din(din),
    .raddr(1'b0),
    .dout(dout_w)
);
defparam m0 .SIM_EMULATE = SIM_EMULATE;


// the tools don't see it, but this is quite possibly unstable - harden it
// revision - if you put synthesis preserve dont_replicate on this it won't pack, removed
reg [5:0] dout_r = 6'b0 ;
always @(posedge dout_clk) dout_r <= dout_w;

reg [5:0] dout_rr = 6'b0 /* synthesis preserve dont_replicate */;
always @(posedge dout_clk) dout_rr <= dout_r;
assign dout = dout_rr;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "4AvUa/AX+twoSNmlxf8DfgbJZtLM0FTYaDfqwIVh58kyS9m523ZPwLwxNf/MAu2Ws24gvNuIWubOgwJDJF/J8SquMj7R1nNyipeKzuCa44Ouq3sVSfXA6vNne7RbKwd87qtqmEuaCdIDSUZZO8uw+CWUHgUS5S0PLelh7tY7EIuUsZeE9mUM9zh2JvtzuWMzW1qicCsSFUI1HHB6Owmf0ylz2E7BXtP0spRRZWMpnQ3o1Lbn6Z/9rA94UUSSWQZ6cCWgdUdkV6/I32LuScotMGGA3XScFuTHILVBkLLA1vEfnuUmRsXXarNQ3MTEMVDlygqDNMsLJHbs2KfVK5S/ykJDWIEPTN97JyytwEkgiEKPeb0KfSyn1SWdG8KDhMcUTG5B1yLNehazS/Syt+PNsfFYZGvVTzEGPpPgCwMM7vPtdICO4oHCCeq19YKcFbfMuRejhwwpq8du9jl44T3CxfnCuJ312i8unFDq13aOR1d1DPODgjVJrIkQqLcmPoG2/FdDHMRfuSxsB1KZTNIuy8CDXZhSWCFID0gPXnb0Q6HFBZdz1/HnezqKg6OTr+ri3f8pyx+I3cJMeFURT0tbjKLZyz4OY8BGVwWQCk4Iwo5D6DqndMMdlnIEapzGaeaFm/tmrHgBAU+n5fiNsfouEfdgRMt3AIgKL7pVbFghwxs+FllhO68G/Wcj4M0BZ8BF6zzZO9V4s4Wp5t5cZyFQtP9zp7gae8MgzXFts17BP0Qi3DWljkTLFbSBDiXLe+9eqLHAmHHcx5VSLcTm1PK11JP6JpnG8lvvsleAfSP1gik7yVGI60iLQF3A87sWH+TTsh09s33Ynd/hKnmrA9J/5lPWG4qbXbfzW4//TNvzc45muSxJqtDjv1j2ZkLw9FMYpdhlsecH68vE+4X7e/w5jqU5JRokeUx1bxtSOjIac02yYMmCf3sFc/GdIJ6GHJ+gNBsbt0kVJ6WKp1tPyhMUdNEuSQyiwRdQiOr+UDogvWE8oZY/Ll/M6yPAYt2hXnxg"
`endif